### ISSUE TITLE
Update Swagger Definition

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#1]
Hi @swapzone, I found that the definition of TripSegmentContainer and TripSegmentData are not matched with data from mock server.

- TripSegmentContainer.alternatives is an array of array of TripSegmentData. ( array inside array )
- TripSegmentData: alternatives are returned from server but it's not included in the definition. Also timingAlternatives and pricingAlternatives are missing from server data

**Comment by swapzone** [comment]
I updated the mock data, but still have to update the Swagger definition:
- TripSegmentContainer.alternatives must be an array of array of TripSegmentData
- TripSegmentData: alternatives must be included in the definition
- TripSegmentData.timingAlternatives and TripSegmentData.pricingAlternatives are optional

**Comment by davidtran** [comment]
👍

**Comment by swapzone** [comment]
I updated the Swagger definition:
- TripSegmentContainer.alternatives is now an array of arrays of TripSegmentData
- alternatives must be removed from mock data, since it is not used anymore
