### ISSUE TITLE
Implement navigation between different screens

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#10]
In the screenshot you can see the tabs at the top of the list of itineraries. Let's use those tabs as navigation. The first tab leads to the itineraries overview, the seconds one leads to the travel options and the third one will be the booking screen. 

When the user clicks the return button in his browser, the navigation must work as well.

![screen shot 2016-06-18 at 10 33 07](https://cloud.githubusercontent.com/assets/5637811/16169914/269e8f9e-3540-11e6-85ae-83b1e511e339.png)

**Comment by swapzone** [comment]
If I select to include the return trip in step 1 and then go to step 2, everything is perfect. But when I go back by clicking on the first tab ('01. SELECT ITINERARY') my selection of the return trip is gone.

**Comment by swapzone** [comment]
I would also like to cache the appointments. When the user goes back to the search screen, the appointments he has entered should be still there.

**Comment by davidtran** [comment]
Actually when user go back to step 1, the website send a new search request. That's why the return trip gone. 

I think we should still send new trip request, but remember the selection of return trip and request for it and show it as well.

**Comment by swapzone** [comment]
Why should the website send a new search request?

**Comment by davidtran** [comment]
I think it's always good to send new search to request, so we can update price, booking link. Sometimes user stay on the trip page too long, these info can be outdated.

**Comment by swapzone** [comment]
Alright, then we should have the caching in our back end. Good with me. But the selection should still stay the same but only prices and booking links are updated.

**Comment by swapzone** [comment]
Works really well!
