### ISSUE TITLE
Book and Go-Site: Appointment data are missing in the header of a trip

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#101]
In the book and go section, it would be easier to understand what you see here, if we would 

either
- add the appointment name and destination address above the itinerary or somewhere below the calender data in the left pane:
![image](https://cloud.githubusercontent.com/assets/11087531/17434063/8a572df0-5b08-11e6-9e0c-6c2a83d22d72.png)

@damianmartone 
or 
- maintain the navigation like on the other pages before, where we could show the appointments in the left pane and display the current page in the center pane. 
Currently, the book and go-page is nice and clean, but it is not to easy to navigate and to understand if you have 3-5 meetings in a row.

**Comment by damianmartone** [comment]
we could have a summary as a quick-view of whats happening that day, but I would most certainly not take it back to the edit screen styles

**Comment by GrosR** [comment]
A summary is fine, it helps the user to keep the overview in case he entered more than 1-2 appointments

**Comment by damianmartone** [comment]
ok ill prepare this tomorrow

**Comment by GrosR** [comment]
thanks

**Comment by damianmartone** [comment]
@GrosR @davidtran its done in the templates

<img width="1192" alt="screen shot 2016-08-11 at 11 20 22" src="https://cloud.githubusercontent.com/assets/8942032/17584280/ea547c88-5fb5-11e6-8a7e-70ccf979efa2.png">

**Comment by GrosR** [comment]
cool, looks better now :-)
