### ISSUE TITLE
Start Screen - Workflow issue

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#104]
Hi @damianmartone, 

I am testing the current start screen and I am still not satisfied with the appointment card workflow. Basically everything works fine now. 
I think the workflow would be better if we have the "Add another appointment"-Button in the card and move the search button below the appointment cards.

Here is why
- if you enter your last appointment and want to search, I would find it more convenient and natural to have the "Search"-Button not in the card but below the cards. I almost always hit the "Save and add new appointment"-Button even at the last appointment and then remember that I should have clicked the "Search"-Button instead. 
- At the last appointment you want to enter, you would not hit a "Add new appointment"-Button, as you assume that the card will be saved anyway when you leave the appointment card and hit the "Search"-Button below all cards. 

The **Search-Button in the appointment cards** also gives you some irritation, especially when you **edit** a card, as it is not quite clear, if you have to save the edited data somehow, so you click "Save and add another appointment" ... but you can´t hit Search in the empty appoijntment card, as you have to enter data there first. 
So you delete the latest empty appointment card and open the last appointment automatically by this action to have a search button to click on. 

What is your opinion?

**Comment by damianmartone** [comment]
yeah I think some of the edge cases might have proven that it wasn't the best solution, so I'd be ok with leaving it outside the cards, but disabled until at least 1 card (appointment) is full.

**Comment by GrosR** [comment]
makes sense

**Comment by GrosR** [comment]
We should chnange the behavior like this: 
- remove the "Search"-Button from the appointment cards
- put the "Save and Start Search"-Button below the appointment cards, so that you have to leave an appointment card to click "Search"
- deactivate the "Search"-Button until at least one appointment card is fully edited

The appointment card shall have the "Delete"-Button and a "Save and add new Appointment"-Button.

**Comment by damianmartone** [comment]
yes
