### ISSUE TITLE
Select itinerary - Business rule for multiple meetings at the same place

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#111]
A common scenario in business travel is, that you have more than one meeting at the **same customer**, e.g.  
Appointment 1, Department A : **16.08**.2016, 9 AM - 11 AM
Appointment 2 Department B : 16.08.2016, 11:30 AM - 2 PM
Appointment 3 Department A : 16.08.2016, 3 PM - 6 PM
Appointment 4 Department B : **17.08.**2016, 8 AM - 4 PM
Appointment 5 Department C : **18.08.**2016, 8 AM - 6 PM

In this scenario, there is not travel in between Appointment 1 - 3, so we can just show the appointments in the left pane. For appointment 2 and 3, there are no travel options to be selected, as the user has already arrived with the 1st appointment. We should therefore just display the heading for these appointments and a preselected route card with the title "No travel - you are already at the appointment location".

But we need an overnight between Appointment 3 and 4 and Appointment 4 and 5, because the location stays the same but the start date changes. 

If an overnight is required after an appointment, we must assume 
- that the starting destination for the trip to the hotel will be the meeting location
- that the starting location for the earliest appointment at the next day will be the hotel location

This rule must be applied for all overnights.

**Comment by davidtran** [comment]
I think if the distance between appointment A to appointment B is less than 10KM, we can assume that they are in the same location. How do you think ?

**Comment by GrosR** [comment]
you would still need to show an itinerary on how to move in between the locations. But a simple Google map link would be sufficient.

**Comment by davidtran** [comment]
About this sentence: "that the starting destination for the trip to the hotel will be the meeting location"

the starting destination is the starting location ?

**Comment by GrosR** [comment]
You are right, I should have written:
The origin for the trip to the hotel should be the appointment location of the appointment, where you need an overnight.

For the appointment on the next day, the origin must be the hotel location , as you have to get from the hotel to the next appointment
