### ISSUE TITLE
Select itinerary - No Appointment - Return flight 

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#113]
When one selects to take the return flight of there are some days between an appointment and the next one, we must update the departure location of the next meeting to the return destination location. 

So, if somebody started e.g. in Palma de Mallorca
- and had some appointments in Munich and decides to take the return flight option
- the return flight must start from the current appointment location and must have the destination location set to Palma de Mallorca

![image](https://cloud.githubusercontent.com/assets/11087531/17642750/3bc74976-6153-11e6-85e3-38d5e95e2135.png)

Addiitonally, the starting location of the next appointment must be changed to Palma de Mallorca, too. 

This is not the case at the moment. 

![image](https://cloud.githubusercontent.com/assets/11087531/17642752/51112cfc-6153-11e6-840d-b171072a04d0.png)

![image](https://cloud.githubusercontent.com/assets/11087531/17642754/5ec32f62-6153-11e6-81c5-aa29d7713438.png)

**Comment by davidtran** [comment]
So now we have 2 return flight. What if user changes the departure location of the first appointment ? We change the destination for both of them ?

**Comment by davidtran** [comment]
If user change the destination of any trip.. do we have to change the origin of the next trip ?

**Comment by GrosR** [comment]
With return tripss, a change of the departure location becomes more complex, you´re right. We should handle it like this: if a user changes the departure location and

- we have 1 return trip, we should ask the user, if the return trip destination should be modified to meet the new destination, too. If the user confirms, we should modify the return trip destination. If he selects "Discard", we should keep the return trip destination. 

- we have > 1 return trip, we should show the user all affected return trips in a list. Each return trip should habe a checkbox, which is by default selected. 
We should ask the user, if the return trip destination should be modified for all checked items to meet the new destination, too. If the user confirms, we should modify the return trip destination. If he selects "Discard", we should keep the return trip destination for all

**Comment by GrosR** [comment]
If the user changes the destination of any trip, we have to change the origin of the next trip. In case the user has a hotel in between the starting location for the next trip depends on the hotel, else it depends on the last meeting. 
To make it transparent for the user, we should do it like described above: 

if a user changes the destination of a meeting, we should ask the user, if the origin of the next meeting should be modified to meet the new destination, too. If the user confirms, we should modify the origin of the next meeting. If he selects "Discard", we should keep the origin of the  next meeting.

**Comment by davidtran** [comment]
so when user select a hotel, We ask user if he want to change the origin of the next meeting to location of hotel.

**Comment by GrosR** [comment]
yes

**Comment by davidtran** [comment]
Deployed on 17-8
√ Change the origin of next appointment when user choose return flight.

Other tasks are not related to No appointment will be fixed in another issue
