### ISSUE TITLE
Select itinerary - No Appointment - Hotel Selection

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#114]
The hotel selection does not allow a "Double Click" to have the same behavior like "Click + Next Button". 

Please add the double click behavior

**Comment by davidtran** [comment]
Can you confirm this issue again ? I have tested on FireFox and Chrome and it works as expected.

**Comment by GrosR** [comment]
I tested on Edge and Chrome and double click does not behave like "click + next"-Button: 
![image](https://cloud.githubusercontent.com/assets/11087531/17658912/22fc5c7e-62cf-11e6-9aec-5b7a806dafda.png)

If you double click on "return flight, it adds a return flight but does not move next. 

If you double click on "stay in hotel", it adds a hotel blocker, but does not move next. 

If you double click on "Add appointment", it opens the add appointment dialog. This behavior is the same as with a single click and is correct, as you have to enter appointment data. Still, the styling is corrupt if the browser windows is reduced to less then 1110 px. 
![image](https://cloud.githubusercontent.com/assets/11087531/17658995/e293f588-62cf-11e6-93c6-5bdd83f0d69c.png)

if you double click on "Do nothing", it selects the item but does not move next.

**Comment by davidtran** [comment]
ok, I understand, I thought you were talking about the hotel section in trip options. I didn't see the NO appointment title.

**Comment by GrosR** [comment]
still does`t move to next

**Comment by davidtran** [comment]
Fixed
