### ISSUE TITLE
Select itinerary - No Appointment - Add Appoinment

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#115]
If you edit the start date or time in the dialog, the end date and time is not updated. 

![image](https://cloud.githubusercontent.com/assets/11087531/17642776/415912d8-6154-11e6-8279-8f322cc8d853.png)

The end date should be set to the same date as the start date in case the start date gets modified. It shall still be possible to change the end date to a **later** date afterwards. 

The end hour should be set to start hour +2 by defauilt

**Comment by davidtran** [comment]
I can't reproduce this issue yet

**Comment by GrosR** [comment]
seems to be vanished
