### ISSUE TITLE
Select itinerary - No Appointment - Add Appoinment

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#116]
If the user adds an appointment in the No Appointment Option and there are still more then 1 day left in between the new appointment and the next appointment, we should another "No appointment"-Block after the newly created one. 

We do not need this behavior for the other options. because: 
- with a return flight, we assume that the user will be at the office
- with a hotel, we assume he stays at that place unitl the next appointment
- with do nothing-option, the user wants us to skip

**Comment by davidtran** [comment]
@GrosR  So, in the no appointment options dialog, if you select "Add appointments" and the new appointment still have a gap with the next appointment, we need to create another "No appointment" ?

**Comment by GrosR** [comment]
yes. 
Imagine a scenario where somebody planned appointments for Mo, Tu and next Monday. So he has a gap from Wednesday to Friday before the weekend. 
Once someone starts to add an appointment in the time range from Wednesday to Friday instead of skipping or returning to home, it is likely or at least possible, that the user might want to add other appointments between Wednesday and Friday.

**Comment by davidtran** [comment]
Should we restrict the datetime of new appointment ?

I think it should not be less than the previous appointment.

**Comment by GrosR** [comment]
Makes Sense

**Comment by davidtran** [comment]
Deployed on 17-8

**Comment by GrosR** [comment]
I added a new appointment to test the date restriction and saved a valid appointment. When saving the appointment, this dialog pops up: 
![image](https://cloud.githubusercontent.com/assets/11087531/17751377/24cb0df8-64c7-11e6-981e-c6d6cf5fe676.png)

The message content is empty, but should aslk, if the origin of the next appointment or, if the next appointment is a return flight, if the origin of the return flight shall be changed.

**Comment by davidtran** [comment]
Done.
