### ISSUE TITLE
Select itinerary - No Appointment - Do nothing

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#117]
If a user selects "Do nothing" in the "No appointrments"-Option, we still have to update the Starting location for the next meeting, as the user will probably not stay fpr days at the last appointment location. 

As we  do not know where the user is going to start from to the next meeting, we must somehow show the user that the starting location for the next meeting must be checked. 

@damianmartone  Can be "mark" an appointment as "dirty" so that the use is aware that the starting location needs attention`?

**Comment by damianmartone** [comment]
not so sure its the right way, if the user HAS to change the departure date, then what we should do once he chooses that, is to trigger the appointment edit mode for the next appointment with a helping text that says "Please confirm your departure location now that you've decided not to take a hotel or flight back between your latest appointment and this"

**Comment by GrosR** [comment]
Yes, opening the appointment edit dialogum for the next appointment makes sense

**Comment by damianmartone** [comment]
close moving discussion to https://github.com/clowdfish/ttg-frontend/issues/128
