### ISSUE TITLE
itinerary selection - styling bug

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#119]
if I reduce the width of the browser so that the with of left pabe + center pane is reduced ro < 1110 px, the "Change"-Link does not look ok: 

Ok: 
![image](https://cloud.githubusercontent.com/assets/11087531/17658775/467c298c-62ce-11e6-99d8-7586889e4e3b.png)

Not ok: 
![image](https://cloud.githubusercontent.com/assets/11087531/17658794/6b3ab324-62ce-11e6-9076-0827bf7c3d8c.png)

**Comment by davidtran** [comment]
it should be an icon instead of a text, text takes too much space.

**Comment by GrosR** [comment]
we could use "Edit" instead of change.
