### ISSUE TITLE
Change button logic in travel options screen

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#12]
In the travel options we have the Previous and Next button at the bottom. This buttons only make sense, when we have multiple appointments. 

I would completely remove the Previous button and use the next button to go to the next screen (as it is implemented currently). What do you think?

![screen shot 2016-06-18 at 10 44 43](https://cloud.githubusercontent.com/assets/5637811/16169961/b29e64dc-3541-11e6-805e-d2adbbf53f18.png)

**Comment by davidtran** [comment]
Agree

**Comment by davidtran** [comment]
The navigation buttons work like this:
Previous button doesn't show if user is at first appointment.
Click on next button will go to next appointment.
If it's the last appointment, click on next button will go to booking screen.
How do you think ?

**Comment by swapzone** [comment]
Cool! We could even make the next button change to Proceed once we are at the last appointment.

**Comment by davidtran** [comment]
That's great.

**Comment by swapzone** [comment]
Cool!
