### ISSUE TITLE
Detect the timing overlap

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#121]
When choosing the start time and end time of any appointment. We need to make sure that there are not overlapping appointment.

For example:
Appointment A is start from 15h and end at 18h on 17-8
If user create another appointment which overlap with timing of appointment A, we need to warn user.

**Comment by GrosR** [comment]
yes, I realized this, too. WE should inform the user and let him decide if he still wants to save the appointment, even though it`s overlapping, or if he wants to modify the times
