### ISSUE TITLE
Change origin of first appointment will affect to destination of other return trips

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#122]
From @GrosR :
With return tripss, a change of the departure location becomes more complex, you´re right. We should handle it like this: if a user changes the departure location and

we have 1 return trip, we should ask the user, if the return trip destination should be modified to meet the new destination, too. If the user confirms, we should modify the return trip destination. If he selects "Discard", we should keep the return trip destination.

we have > 1 return trip, we should show the user all affected return trips in a list. Each return trip should habe a checkbox, which is by default selected. 
We should ask the user, if the return trip destination should be modified for all checked items to meet the new destination, too. If the user confirms, we should modify the return trip destination. If he selects "Discard", we should keep the return trip destination for all

**Comment by GrosR** [comment]
this will be covered by #128
