### ISSUE TITLE
Select itinerary - general handling of improper situations in between dates

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#126]
As we allow the planning of multiday, multi appointment trips, which is what business travelers frequently do, we have to decide if we accept improper situations or not. 

As the goal of our engine is to facilitate the complexity of travel planning to make people book through our portal, invalid travel plans do not make sense. 

Invalid does not mean that we can`t have "overlapping times". As you never know exactly how long meetings take in fact, it might make sense to overlap meeting times. 

But it does not make sense to allow impossible travel options in means of travel. This situation will mainly occur through changes in the "select itinerary" section.  

This part is the most complex one from the FE.application perspective, still the complexity helps users to manage complex trips. We can`t skip that from my perspective. 

What we can still do is to limit the possible change scenarios:
- changing the origin of an existing appointment means that we have to check the meeting location of the meeting before. 
- changing the appointment location will affect the origin of the next meeting
- adding appointments in between will affect the meeting before and the meeting after - still, it is just a combination of what we do anyway in the change situations above
- adding a return trip in between affects the next meetings origin 

In any of these cases the question for any appointment card is
- start from origijn
- start from hotel 
- start from last meeting
- start from an individual location

As we can`t decide für the user, we should guide the user through the appointment cards that are affected. This means: 

If a user applies one of the changes from above, we should save the change and then ALWAYS open the affected appointment card in edit mode and highlight the field that has to be validated by the user. We can inform the user why thsi happens by a message in the card. 

This should streamline the process and allow us to implement ONE SET of rules that will always result in the same bahavior.

@damianmartone what is your opinion?

**Comment by damianmartone** [comment]
close moving discussion to https://github.com/clowdfish/ttg-frontend/issues/new
