### ISSUE TITLE
Simplify flow for location changes, "no data" appointments

### ISSUE THREAD

**Issue by damianmartone** [clowdfish/ttg-frontend#128]
As spoken with @GrosR on skype on the end of last week, this is what we came up the final version should look like

1) Home Screen: 

Cards will all be the same and will have origin and destination
<img width="1161" alt="screen shot 2016-08-22 at 17 22 21" src="https://cloud.githubusercontent.com/assets/8942032/17860307/4cf03190-688d-11e6-9666-088e03ae450f.png">

After the user opens a new card (meaning he has completed at least 1 appointment, the destination of the first card, will be copied as origin for the second, and the focus on the card will be on the APPOINTMENT LOCATION text field, but still the DEPARTURE LOCATION will be editable by the user in case he decides to change it.

<img width="1132" alt="screen shot 2016-08-22 at 17 25 59" src="https://cloud.githubusercontent.com/assets/8942032/17860395/b0f8d278-688d-11e6-9c17-096e3ea271b5.png">

Flows goes normally from here on, so editing each card can edit both origin and destination.

-----

2) Changing appointments on Itinerary Screen

The user can modify the location like before, pressing on CHANGE and editing the screen, but the button is now "Apply Changes" after this happens, the whole itinerary needs to be re-done and the user will start from appointment 1 all over again, because we need to confirm that he sees the changes the appointments bring, but we need to remember his preferences. Also we remove the hotel option.

<img width="1199" alt="screen shot 2016-08-22 at 17 50 24" src="https://cloud.githubusercontent.com/assets/8942032/17861328/ed78d380-6890-11e6-89d9-6a06592d6922.png">

This means that now when the user edits the card, he will be able to say "fly back home after this appointment" or "dont book anything after", the second one means, that if the card next to this appointment has an appointment happening in Madrid, the origin city will also be Madrid, cause the user told us "dont worry about how, i will get there myself"

If origin=destination trip will cost nothing, have no booking link, cause the user doesnt book this with us or does it his way (for example rents a car?)

------

3) No information about what to do between two appointments

![screen shot 2016-08-22 at 17 47 04](https://cloud.githubusercontent.com/assets/8942032/17861417/4e062a04-6891-11e6-8048-ece499ce6dbc.png)

Since we are removing hotel options from this screen too, we ask if he wants to book a return flight.train, book a flight/train somewhere else, do nothing (which means the origin in the next appointment will be the same as destination) or add another appointment between these days.
We have to define a default, if we say by default we always fly him back "home" then if the user selects another option, the "next" has to change also for "apply changes to my itinerary" and redo the itinerary since its basically the same as changing one card (the next one) 

----

4) Upgrade options (travel options)
This screen disappears for now, no hotel selection, and flight upgrades can be done from the select screen, so no need for this anymore

----

5) Booking screen
Main change here is hotels will be handled by affiliate so instead of hotel price etc, we'll show a booking link to our affiliate partners (for example booking.com) we can also add a logo, basically looks like this

<img width="834" alt="screen shot 2016-08-22 at 18 00 11" src="https://cloud.githubusercontent.com/assets/8942032/17861703/61aaf5d4-6892-11e6-863b-f2e5d0147839.png">

-----

@GrosR please check if this is all what we spoke about or I forgot something.
@davidtran all changes are made in the templates as well in case you need some structure change.

**Comment by davidtran** [comment]
Thank @damianmartone for the new UX
So we have removed the Travel options, @damianmartone You need to update the navigation bar in the template too too :)

Question:
**On home screen:**
- Do we still sort appointments based on appointment time anymore. I think we should not do it. 
- We also need to restrict the start time of new appointment. It should not greater than the end time of the previous appointment.

**Itinerary screen**
- When user change the destination of an appointment, do we need to set the next appointment origin at that appointment ?

**Comment by GrosR** [comment]
@damianmartone Looks like what we said and I think this is the best we can deliver at the moment. We can perhaps add a map view in the result to show the map for a single trip and he whole trip to beautify things. We could add the map feature to links on the left or a tab to select on top if a card to let the user toggle between map and text view in case he wants to see the map. 

Still, the flow like it is should be the best start for now. 

@davidtran 
home screen:
- We still sort the meetings based on the timings of the meetings as a user will think about his appointments like he does in his calendar. 

If the user exports his plan later as ics-file and opens it in Outlook, he will expect to see the same sequence in the calendar then in the trip planner. 


- We keep time restrictions as described and implemented already

itinerary screen:
- a change in a card leads t a complete recalculation of the trip. As the user has to walk through every single card again to confirm origin and destination, we don´t need to change the origin of the next card. 
The user has to use his brain in this case and check, if the origin is valid. 

We will see from the real users behavior if users expect another behavior.

**Comment by davidtran** [comment]
I don't see the return location at the homescreen anymore. Do we still keep it ?

![screen shot 2016-08-24 at 10 13 35 am](https://cloud.githubusercontent.com/assets/1154740/17917114/81f3b932-69e3-11e6-93db-655fa8f3acb2.png)

**Comment by GrosR** [comment]
yes, we should keep that..

**Comment by davidtran** [comment]
How about the departure location on the top. I didn't see it too.

**Comment by GrosR** [comment]
As the departure location is included in the cards, the departure location apart from the cards is no longer needed. 
The screen will start with an empty appointment card

**Comment by davidtran** [comment]
Hi @damianmartone 

What if user select: "PREFER TO FLY BACK TO MY ORIGIN POINT" in appointment dialog ?
We create a new appointment and add it to trip list ?

**Comment by damianmartone** [comment]
like I said on the email, yes 
theres a style defined for return
<img width="372" alt="screen shot 2016-08-30 at 10 09 42" src="https://cloud.githubusercontent.com/assets/8942032/18081327/e8c30fb8-6e99-11e6-9bc5-299446fc2d46.png">

**Comment by davidtran** [comment]
@damianmartone I added a small condition. If user choose "Prefer fly back to..." in the last appointment and user also checked the "including return trip..." checkbox in homepage. Only one return trip is created.

**Comment by damianmartone** [comment]
cool

**Comment by GrosR** [comment]
please fix #140 first before I can fully test this
