### ISSUE TITLE
Start Screen - After Returning from Book&Go Page

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#129]
I entered a single appointment and walked to the book & go page. 
I clicked on the 1ClickTrips Icon to return to the start page. 

a) The start page was not cleared, which should be the case

i added two new appointments to the existing appointment, which was not cleared. 

Then I entered an appointment at a location very close to the last appointment. After clicking the search button, I received this screen and the system hang up: 

![image](https://cloud.githubusercontent.com/assets/11087531/18224559/e5d74a6a-71d9-11e6-82e1-4e1e1fa89b6e.png)

**Comment by davidtran** [comment]
@GrosR  I have investigate and figure that this issue happens because Edge can't parse response data from server. I am trying to fix it.

**Comment by GrosR** [comment]
Hi Nam, as this situation happens also when we insert appointments that are at least > 24 hours later than the previous one AND the origin of the last appointment <> previous appointment location, I assume it might be also a logic bug. 

In the previously described  situation, it is not clear how the user will get from the previous appointment to the starting destination of the next appointment. And in case the travel time between the previous and the current appointment location  takes longer than the available time, it might even be an impossible situation from a practical standpoint. In these cases, we should check the feasibility and warn the user. 

In the situation where the appointment locations are very close together, it might be a similar issue. If the system tries to get a trip and there is just a walking distance in between the locations, it might cause troubles. 

This shall just be a help to debug.....

**Comment by davidtran** [comment]
Fixed!
