### ISSUE TITLE
Make hotel list scrollable

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#13]
Currently we only show three different hotels. But we will most probably want to show more than that, so the user must be able to scroll through the list of hotels.

![screen shot 2016-06-18 at 10 46 46](https://cloud.githubusercontent.com/assets/5637811/16169971/fa9a6632-3541-11e6-944c-896b2002daa6.png)

**Comment by swapzone** [comment]
Okay, I did express myself completely wrong. I was thinking of a horizontal scrolling of hotels. Can you implement that instead of the vertical scrolling?

**Comment by davidtran** [comment]
okay, I got it

**Comment by swapzone** [comment]
Tested and done.
