### ISSUE TITLE
Start Screen not cleared correctly

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#131]
If you click on the 1clicktrips-Logo, the screen must be cleared to show en empty card. This does not happen: 

![image](https://cloud.githubusercontent.com/assets/11087531/18230697/563deba4-72a4-11e6-9fcc-246bdc8c3a15.png)

If there is just ONE card displayed, the "DELETE"-Button must be labelled "CLEAR CARD" instead of "DELETE" and it must not be possible to really delete the inital card. 

As soon as more then 1 card is displayed, all cards must show the "DELETE"-Button. As soon as all cards but 1 are deleted, the last card must display the "CLEAR CARD"-Button again. 

At the moment, you can delete the inital card. 

![image](https://cloud.githubusercontent.com/assets/11087531/18230699/6c2d684a-72a4-11e6-9b9b-9eeb6630049e.png)

This is wrong.  If you click on "Edit" then, the screen looks like this: 

![image](https://cloud.githubusercontent.com/assets/11087531/18230703/85666e38-72a4-11e6-8247-9d1c2ac47cf5.png)

If you click on the return destination in this screen, the "Change return destination" Dialog pops up, even though there is not a single appointment card left: 

![image](https://cloud.githubusercontent.com/assets/11087531/18230712/b3cf2076-72a4-11e6-9954-120e007de6c8.png)

From there, you can not return to the initial state, so you can´t cancel this action by pressing the ESC-key or clicking somewhere outside the "change return destination" dialog. 

If a user clicks on the return destination, he needs the option to discard the popup-dialog. Please add two buttons; "Discard" and "Save".

**Comment by GrosR** [comment]
doesn´t woirk with Edge

**Comment by davidtran** [comment]
This issue happened because Edge cache data
