### ISSUE TITLE
Select itinerary screen - styling bug

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#133]
In the left pane, the end-date and time are styled with an underline. This is not expected. 
![image](https://cloud.githubusercontent.com/assets/11087531/18230791/56179f9c-72a6-11e6-8487-488d1aed3402.png)

There is also a black frame border left and right, which is not expected there: 

![image](https://cloud.githubusercontent.com/assets/11087531/18230796/7a240a74-72a6-11e6-809c-8158c676965e.png)

**Comment by davidtran** [comment]
Which browser did you test ?

**Comment by GrosR** [comment]
I used Edge and Chrome

**Comment by davidtran** [comment]
It would be great if you can give the step to reproduce this issue. I have tried to create various appointments but still can't reproduce this issue.
