### ISSUE TITLE
Select itinerary - sort order

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#134]
We should sort the route cards in an order. I would like to have the cards ordered ascending by the duration of the route (spent time for the trip). 

We should also add icons for any form of transport. In our mock data, we are missing symbols for car, rental car, Taxi and Uber. 

We can add an option to "resort" the route cards by price. 

To do that, we can add two links on top of the route cards that look like that: 

_sorted by_:  **duration**   price  **asc** / desc

**Comment by davidtran** [comment]
Already done via #199
