### ISSUE TITLE
Book & Go Screen - Return flight

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#136]
The appointment card in the Book and Go - Screen does not make too much sense. 

The current card lloks like this: 
![image](https://cloud.githubusercontent.com/assets/11087531/18230963/21ee8ea6-72ab-11e6-8f9e-739df17e7faf.png)

As the return flight has no appointment, but juts a trip and the arrival, the return card must be as special as the the return trip card in the sidebar in the itinerary selection. 

1. The text in the route must not be "Drive to Appointment" - it should be like with the flights: 

[Traveltype] & from [Start] to [Destination], where [traveltype] can be:

Taxi: "Take a taxi"
Uber: "Take a Uber-taxi"
Train" "Take train # [trainnumber]"
Car/Rental-Car: "Drive"
Flight: Take flight # [flightnumber]"

2. The symbol for the arrival at the return destination should be like in the itinerary selection: 

![image](https://cloud.githubusercontent.com/assets/11087531/18231002/3c7247b2-72ac-11e6-879c-f7b790ee5584.png)

**Comment by davidtran** [comment]
The backend doesn't provide train number and flight number now.

**Comment by davidtran** [comment]
Done. I will update train number and flight number when backend provides. it
