### ISSUE TITLE
Start Screen - Checkmark at Return Trip not cleared

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#141]
When you click on the "Return trip" Checkbox, the return destination is cleared, buit the checkbox is still marked. 

The checkbox should be cleared, too. 

tested with Edge. 

With Chrome and IE11 it works fine

**Comment by davidtran** [comment]
Could you please give me a screenshot ? I am testing with Edge and it works.

**Comment by GrosR** [comment]
I just found out that it is a Cache problem of Edge. I could reproduce the error with the same browser session I had opened yesterday. I closed all Edge windows and cleared the cache and now it works. 
It seems that Edge caches much more aggressive than the other browsers

**Comment by davidtran** [comment]
Cool, so I close this issue.
