### ISSUE TITLE
Origin in following trip is not updated after selecting an item in the option card

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#144]
I entered two appointments with 3 days in between. 1ClickTrips adds a "buffer card" correctly and asks, what I want to do in between. 

I selected return to origin and selected a return flight. 

The following card has not been updated, but it makes no sense to let this card start from the former origin. 
If the user does not select "Do nothing", 
- Ideally, the process would succeed at the first invalid card in the process, which should be the next one after the choice taken before. The system should show what is invalid, which is clear from the choice taken before: 
- return flight/another appoinmen/ another destination chosen: origin of next sppointment is wrong
else just go to the next card.

**Comment by davidtran** [comment]
Here is the changes that we will implement in this issue:

1. When user selects "Add another appointment", we show appointment dialog, after user clicks "Save", we add new appointment and update the location of appointments before and after this appointment.

2. When user selects "new destination", we update the destination of this appointment and also update appointment of the next appointment. We go to the next appointment and show a message to let user know that he should check and update the next appointment.

3. When user selects return to origin, we update destination of this appointment to origin and change start location of next appointment to origin location. Go to next appointment and show a message.
