### ISSUE TITLE
Display hotel booking link when segment.end.type === 0

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#147]

**Comment by GrosR** [comment]
what do you mean here? You don´t get information from the system, here? IF so, you should ask Sascha what the system should deliver.

If this is a question to me.... what information do you need?

**Comment by davidtran** [comment]
Sascha didn't actually hotel segment in the search result. But when the value of destination.type of segment is zero. It means the next segment should be a hotel segment.

So on the frontend, when it encounter a segment like this, it creates a hotel segment and shows it. Although it doesn't have the booking link from server but we can customize it and add affiliate code into our link.

**Comment by GrosR** [comment]
at the moment, it doesn´t seem to add hotel links at all.... but of it does, we can do it like you siad

**Comment by davidtran** [comment]
We will generate the hotel booking link from FE.
