### ISSUE TITLE
Changes in book & go screen

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#148]
I completely forgot to ask for some changes on the book & go screen. 

I would like to replace the "Print this" and "E-Mail this" Link by an icon and add the icons for Google-Cal Export and Outloook Cal Export where you see the squares. 

In the lower left corner, it makes sense to show the whole trip in the map. once a user selects a specific trip segment, the map can size to show the specific map for the segment, if the user clicks on the date in the upper left corner, the map will show full trip again. 

![image](https://cloud.githubusercontent.com/assets/11087531/18711331/bdc00dbc-8009-11e6-92eb-65cfe87c509a.png)

**Comment by davidtran** [comment]
I am afraid that area is too small to show a map

**Comment by GrosR** [comment]
II think it´l require a little redesign of the zones to show a contect sensitive map.. but we had that in the old version and I found this useful. 

In this version, where the user has a very good overview of his booking steps, it will be helpful, too, to see the whole trip and specific trip details before booking. 

I hope that Damian will have a good idea from a design and UX perspective. Perhaps wie nees to add the map somewhere else, e.g. on top of the bopoking steps

**Comment by damianmartone** [comment]
I still don't completely understand the use of the map here... no airline or travel site shows you a map of anything when you are booking. Its also not usable to travel because its small and might be too zoomed out so a line between cities is a bit irrelevant, and I think would make the clean design be busy and confusing.
If you can explain what exactly would be the purpose of a map, I can consider if its necessary in this or other step, but if its just as a representation with no functionality, i would vote for no map.

**Comment by damianmartone** [comment]
Did these changes in the book & go section to go along with the ones in the itinerary we made before
@GrosR please take a look if you see anything missing, then we can begin implementation

<img width="1019" alt="screen shot 2016-10-10 at 13 06 16" src="https://cloud.githubusercontent.com/assets/8942032/19234215/72b60692-8eea-11e6-9e86-da117d44c25b.png">

mobile
<img width="376" alt="screen shot 2016-10-10 at 13 06 28" src="https://cloud.githubusercontent.com/assets/8942032/19234216/72bda9ec-8eea-11e6-99cf-df9403729775.png">

**Comment by GrosR** [comment]
Hi Damian, 
after some changes in the itinerary section, I think we can omit the extra cost segment at this time. 

We found out, that there are several use cases, where we can´t differentiate between regular trip cost and extra cost. This is mainly as we sometimes have to information on price and details for train, which leads to situations, where a train is listed in the trip and also in the extra cost segment. This is confusing. 

I also think, that the description below the appointment name does not match this page. It should be more sth.: This is your trip overview, ready to jump to your booking.

On the mobile screen, it should be clear if there are more than one segments that can be booked, so that a user does not jump away and looses track of further booking options for his trip.

I´d also be happy to give the user a whole trip overview for a travel day, including timings and walk. This can be done e.g. in the print or be attached in the .ics body´. 

If we leave the user without a trip map, he has no reminder that he booked with us. Later, we are ging to this of course in an app.

**Comment by damianmartone** [comment]
ok about excluding the extra costs, here they are smaller and less notorious but if you prefer they don't show, we don't show them

we can add a "booking 1 of 4" before each title so its clear on mobile that they are multiple things to book but I wouldnt change the layout with complexity or more icons, since this is a quick link to the bookings

the whole trip overview would be fine, but that shouldnt be the booking screen but a printer-friendly screen with the information, here price is not relevant anymore, and neither are booking links, but I think its a separate screen for that

> If we leave the user without a trip map, he has no reminder that he booked with us. Later, we are ging to this of course in an app.

what does this mean exactly?

**Comment by GrosR** [comment]
- extra cost would be fine, if we could identify them clearly from the data.. but we can´t at the moment, that´s why I would remove this now and add it later, once we have better data, 
- I don´t want to add complexity... I just don´t want to loose customers after the 1st step.... so a navigation that shows the booking steps 1 ..x is good..could also be a progress bar like you showed before. 
- printerfriendly full trip overview without pricing is what will be useful. 
- the last sentence means: a tripmap with our logo and link on it is like an advertisement. The user will remember us, once he used this feature. IF he just uses the online platform once and forgets to mark us as favorite, it is likely that they will never find us again, as we let them jump away to other portals at the moment .. so they get invoices and tickets from other portals and will remember these logos more then ours. 
That is why i am looking for an MVP to be remembered by infrequent users :-)

**Comment by damianmartone** [comment]
ok but I still dont get how the user uses the map feature.. what would he look at exactly?

**Comment by GrosR** [comment]
the idea with the map was as follows: 
- if no trip segment in a "calendar card" is select (default), my idea was to show the map for the whole trip as a line, so that you can see your stations you pass, e.g. Start - Frankfurt Airport - Atlanta - Dallas - Appointment.
- once you click on a specific segment, like flight from ZRH -> PMI, the map would resize and show the destination from Airport to Airport 
- once you click on another Segment, you see the map for this segment

Segment maps would show more details, so that you get a feeling for the distance and environment you´re going to be. 

The idea was to give more transparency over your trip. 
We can skip this of we print a printer friendly travel plan.

**Comment by damianmartone** [comment]
I still feel this doesn't fit in this design, this is a screen with heavy information, we can't have all that info and also a map as a rotative (on select) element, its just too much. If you prefer that the book&go screen has the map with the display of the route as main element, and the details on a secondary level, we need to redesign the screen, but I still feel it would be a mistake.

The main functionality of the screen is seeing what you need to do each day, the times and how much it would cost, so I feel we should keep this screen telling you this first. I also think business people know the distances and what they get into, so a map is a bit of irrelevant information (especially on the zoom level that we can provide).  And having a decent-size map for each card would generate an even longer page, and the data harder to reach.

To me transparency on a trip is telling the user what to do each day and how much it costs. We could add waitings, layovers, etc, but I dont think a map adds anything to an itinerary.

**Comment by GrosR** [comment]
as said before, we can skip the map if you think it does overload the Screen. As it is primarily a booking screen to tease People to book, I am fine with it. 
More important will be, that we are able to deliver integrated booking and deliver the tickets and trip Details in an app as soon as possible. Ticketing will be the Major challenge, but also the Major driver for customer loyalty.
Thanks for your support
