### ISSUE TITLE
Redesign route cards in itinerary selection

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#149]
the route card is an enhancement or replacement of the current cards in the itinerary selection. 

When we tested with mock data, we didn't realize that it is difficult to decide for a card as a max. of 3 cards with different means of transport where delivered, 

With live data, we get Bus, Train, Taxi and combinations of flights and flights + Train etc. - and it is not possible to see, if a trip starts the day before or on the same day, as only the time of a trip is shown. 

the major goal with the update is to deliver valuable information to compare routes. 

Currently, it is not possible to see,  
- Startdate of the route (important, if the route starts the day before an appointment or the same day)
- total trip time
- trip start time (I want to know if I have to get up at 4 AM or to start relaxed at 10 AM for 20 bucks more)
- total trip price ' starting from '  (in case a user takes the cheapest options)

It is also useful to see how many trip steps you have on a trip..... if it requires to change your transport 7 times instead of 2 to save 20 bucks....you know what I mean..

I personally would prefer a visual representation of the trip steps to show a user how many hops he has to take. This can be done quite basic with a fixed length line starting with a "home" or "mapmarker (a)" to a "destination" or "mapmarker (B)" with "fat dots" for each stop in between... or sth. more sophisticated that shows the means of transport (car, walk, hotel..).

I would find it useful, too, if we could sort the routes by best price and shortest total time & price through 2 icons on the right side above the route cards. 

below, you see an ugly sample of teh information I would like to see on a route card - but with a better design :-) 

![routecard](https://cloud.githubusercontent.com/assets/11087531/18711415/2eca323a-800a-11e6-8eaf-f9e24384f181.jpg)

**Comment by GrosR** [comment]
just to add this....with live data, the route cards sometimes look as complex as this
![image](https://cloud.githubusercontent.com/assets/11087531/18829579/3841ecfa-83dd-11e6-9baa-96bcaa986abe.png)

and you can get 10 - 15 of these cards: 
![image](https://cloud.githubusercontent.com/assets/11087531/18829612/5fb0f394-83dd-11e6-9863-f8a7960477a0.png)

it is almost impossible to understand, which trip is a good one and which not

**Comment by damianmartone** [comment]
well the cards were not originally made to have all that information, probably its a good idea to then make them a simple view and a have details toggling to avoid a lot of vertical information on the page

**Comment by GrosR** [comment]
I think the most important information for the user to be able to compare trips is:

The route information, total trip time, Total cost, #of steps in the trip and start time.. 

Total cost is the total cost "starting at"

I think we can put the details of the trip (segments, means of transport, graphical view etc. to a slide out section.

**Comment by damianmartone** [comment]
This is my suggestion

<img width="644" alt="screen shot 2016-09-26 at 17 01 46" src="https://cloud.githubusercontent.com/assets/8942032/18839346/f34f9ee8-840a-11e6-93c6-68a56cee70b2.png">

I dont think its necessary to be so graphical in the "leave home, walk" etc way since that is happening already in the sidebar view, here its just important that if you go from A to B, here are the possibilities. In a reduced version the user sees the things @GrosR marked as important, the icons, and the possibility to slide in details, with all the rest of the information

**Comment by GrosR** [comment]
Hi Damian, 
Good work, I still have some questions to better understand your idea:

What happens with trips that have more than 3 steps to show the reduced trip visualized in the compact view? Which sections do you select as start..middle ..end ..if you have e.g. Two major trip Segments? The average trip will end with the appointment .. in between appointments , there are 1-2 overnights in the worst case 

I don't understand what you mean with.... leave, home, walk etc. is visible anyway in the sidebar ?  Currently, we have no detailed information about the whole trip including walk, change train or sth. Like that... we just show the rough trip based on bookable items... or do you mean the summary in the book and go screen ?

**Comment by davidtran** [comment]
Hi Damian, 
Great work, now we can see total time and cost on the card. 

Beside that, I think this card is not different from our current card. we have one more click to see major segments information.

About the bus, flight, hotel section in this card. I think we doesn't have enough space to show them. Sometimes, we can have: bus, flight, taxi, train, hotel segments and these icon will go over flow.

**Comment by GrosR** [comment]
@damianmartone Hi Damian, please see our comments. How about adding the trip visuals below the test information and have it like it is rome 2 rio ... as the trips sometimes may have many steps . it could look sth. like this: 

the line could have fixed length for all kinds of trips, only the dots for each segment vary in number. The major trip segments can have a bigger icon. 

![image](https://cloud.githubusercontent.com/assets/11087531/18864958/1baaaa0c-8499-11e6-8269-9013d4bbb59f.png)

The bigger bubbles woudl show the symbol of the major travel means .. and my "design" shall not be a guideline... just a help to understand the basic picture ion my mind. 

If the visual would be below the text information, the # of trip segemnts would not be critical. 

in your current design, I think it can be difficult to visualize it with 3 icons

What do you think?

**Comment by damianmartone** [comment]
So first of all, even when a trip is complex because it offers many steps, I don't think we should display anything that we can't book. 

We have currently a process indicator (sidebar) and a current step (trip from A to B). Its not a good idea to try for everything to be inside one trip card and ignore the rest, the whole interface should explain the user whats going on.

On the first step we see that our departure location is "home" so no need to show this in a card. What we need to show is departure time / duration / amount of changes for the trip, nights in hotel booked, and total price. If there are other details like a taxi ride or things we can calculate, these are things we can highlight in the details for transparency but should not be on the main card or the user might think we are including the price of a taxi, but then we charge less because we don't book that.

We base our progress on appointments, and in each we tell if its just a trip, trip + hotel, return, or nothing. For the user to decide whats more convenient he probably wants to see what brings a lot of hassle, that is more related to the amount of times he has to change, the different means of transport or times.
My previous solution might be too simple but since we are appealing to a business travel, whereas Rome2Rio or GoEuro appeal to a budget traveller, we probably wont have a trip that is 3 trains and a bus to offer. Even if I can build a design that adapts to any, we need to define this because it might make the whole experience different.

With that in mind this is my follow up solution

<img width="571" alt="screen shot 2016-09-27 at 11 01 52" src="https://cloud.githubusercontent.com/assets/8942032/18866825/db61eaba-84a1-11e6-8661-b55324f9eb8d.png">

<img width="547" alt="screen shot 2016-09-27 at 11 01 57" src="https://cloud.githubusercontent.com/assets/8942032/18866826/db641da8-84a1-11e6-9110-46de4350f92e.png">

**Comment by GrosR** [comment]
Hi Damian,


I share your thoughts on the reason why we build this solution and I don´t want to "overinform" the user with to much information, but want to give the user the relevant information in the current workflow step.


In the itinerary selection, the most important dimensions to decide for a business user is "total time", "total price" and "trip convenience". The visuals shall only help to understand "convenience" better.

So, with the latest design, it would also be ok for me to omit the icons and just have the textual information "Flight - Bus - Hotel".


It is also a quite good idea to show the "Non bookable things" separated with cost estimations, thanks for this.


If we follow this logic, we still should think about the "book & go page", where the users wants to book .. and wants guidance for the whole trip. This is why I thought it would be a help to have a map view or detailed trip view (which could also be a link to a google map or sth. like that.


I´d suggest to go forward with your latest design approach like given ...and I´d appreciate to hear your thoughts on the book & go screen

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Inbound Marketing. CRM. Office Produktivität. Portale. Custom Solutions. Ihre Software-Experten für SharePoint|Office365|Cloud und Mobil seit 2005.
Automotive & Suppliers | Industry & Production | Energy | LifeScience | HighTec | TelCo |Health & Medical |Logistics | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: damianmartone <notifications@github.com>
Gesendet: Dienstag, 27. September 2016 11:02:24
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Mention
Betreff: Re: [clowdfish/ttg-frontend] Redesign route cards in itinerary selection (#149)


So first of all, even when a trip is complex because it offers many steps, I don't think we should display anything that we can't book.

We have currently a process indicator (sidebar) and a current step (trip from A to B). Its not a good idea to try for everything to be inside one trip card and ignore the rest, the whole interface should explain the user whats going on.

On the first step we see that our departure location is "home" so no need to show this in a card. What we need to show is departure time / duration / amount of changes for the trip, nights in hotel booked, and total price. If there are other details like a taxi ride or things we can calculate, these are things we can highlight in the details for transparency but should not be on the main card or the user might think we are including the price of a taxi, but then we charge less because we don't book that.

We base our progress on appointments, and in each we tell if its just a trip, trip + hotel, return, or nothing. For the user to decide whats more convenient he probably wants to see what brings a lot of hassle, that is more related to the amount of times he has to change, the different means of transport or times.
My previous solution might be too simple but since we are appealing to a business travel, whereas Rome2Rio or GoEuro appeal to a budget traveller, we probably wont have a trip that is 3 trains and a bus to offer. Even if I can build a design that adapts to any, we need to define this because it might make the whole experience different.

With that in mind this is my follow up solution

[screen shot 2016-09-27 at 11 01 52]<https://cloud.githubusercontent.com/assets/8942032/18866825/db61eaba-84a1-11e6-8661-b55324f9eb8d.png>

[screen shot 2016-09-27 at 11 01 57]<https://cloud.githubusercontent.com/assets/8942032/18866826/db641da8-84a1-11e6-9110-46de4350f92e.png>

-

**Comment by damianmartone** [comment]
Ok yes, if anything the book & go section has to replicate a similar structure but adding the real information selected and not allowing changes

**Comment by GrosR** [comment]
sure..book & go is just for checkout.. not to rethink decisions taken before

**Comment by GrosR** [comment]
@damianmartone wait a little until you proceed, please.... I am just discussing with Nam

**Comment by GrosR** [comment]
@damianmartone Hi Damian, reading the information in the new design is bit harder than before due to the split and segmentation in two lines. What about having the same info like this: 
#
![image](https://cloud.githubusercontent.com/assets/11087531/18871546/1920c362-84b6-11e6-8c89-0b767ade19be.png)

of couse with your design and styles...

But we think it is easier to read, if all info is in one line and you can read from left to right

**Comment by damianmartone** [comment]
sure we can adapt to this
<img width="623" alt="screen shot 2016-09-27 at 14 41 38" src="https://cloud.githubusercontent.com/assets/8942032/18873595/8b93df42-84c0-11e6-87c3-454c7c039d5d.png">

**Comment by GrosR** [comment]
looks good...
There are three information snippets left that are interesting for a business traveler: 
- time left before meeting starts to see, if he has to hurry in the end with this trip
- week day when the trip starts and weekday when the appointment is... so that you see if you start the same day or the day before

any idea to include this clever..?

**Comment by damianmartone** [comment]
I'd add the first one in the folding details, and the second one would be more header before cards.
 For example, I'd prefer we recommend trips departing the same day but we could have

### Departing Monday 12th October
(card 1)
(card 2)

### Departing Sunday 11th October
(card 3)

or so

**Comment by GrosR** [comment]
fine for me....
The trip engine tries to deliver trips that start the same day as the appointment... but if we have no results or just 1, it can happen that we have "day before trips"

can you put "time left before meeting starts somewhere on the cards, still... then I am very satisfied with the result and we can go ahead with dev

**Comment by damianmartone** [comment]
<img width="616" alt="screen shot 2016-09-27 at 15 46 15" src="https://cloud.githubusercontent.com/assets/8942032/18876333/8afe02a2-84c9-11e6-92ba-f5bd547d568b.png">

**Comment by GrosR** [comment]
cool... let´s gp for this version ... it is almost as good as my own first drawing in PowerPoint :-)

**Comment by damianmartone** [comment]
haha ok ill start coding it in the templates repo

**Comment by GrosR** [comment]
:-) Thanks... after this project, I see that my further career as UX designer might get stuck.... :-)

**Comment by davidtran** [comment]
meanwhile, I am gonna UI/UX design to my LinkedIn profile 😎

**Comment by GrosR** [comment]
good plan :-) 
or you can take a look into Kendo UI and talk to Mark (theblackwarrior) about upcoming mini projects

**Comment by damianmartone** [comment]
@GrosR @davidtran cards are ready on the templates repo > itinerary.html
<img width="719" alt="screen shot 2016-09-30 at 21 14 51" src="https://cloud.githubusercontent.com/assets/8942032/19003859/07475c38-8753-11e6-9d26-0af0c1931de2.png">
<img width="539" alt="screen shot 2016-09-30 at 21 14 59" src="https://cloud.githubusercontent.com/assets/8942032/19003860/074a6590-8753-11e6-9415-6effeddf35ad.png">

**Comment by davidtran** [comment]
Thanks @damianmartone 
I am integrating the template into our app.
We need alternatives section. You should update it too.

**Comment by damianmartone** [comment]
@davidtran should just be a popup with a similar list, can use the same styles

**Comment by davidtran** [comment]
I have just deployed too http://app.1clicktrips.com/

**Comment by GrosR** [comment]
due to our latest discussion and tests, we agreed on the following changes to the route card: 
Overview: 
- timing shall be displayed in 24 hours notation instead AM/PM
- total cost will be renamed to ~ Total cost and will contain all bookable and estimated cost
- other cost will be renamed to overnights and will display the number of overnights
- sort shall be done ASC on total trip time first, 2nd criteria is Total Price

Details: 
- As we found out, the trip data can´t be separated by "bookable" and "non bookable other cost", because we have main segments in our trips (e.g. trains) where we still can´t book, we decided to not differentiate between bookable and non bookable cost. 
- Additionally, the number of changes is irritating as it shows alle segments including walking, which makes sense.... but in detail, you just see the transports ...which is irritating, as you see e.g 7 changes, but only 2 transport segments. 

We therefor decided to display all trip segments including timing information, so that the users can see the whole trip in the detais, including timing (departure time, arrival time, duration), departure location - arrival location transport provider and transport-Nr.,, Tarif and Price, e.g. 

Start 08:23
Walk  08:23 - 08:40  00:17 h  Home - HBF Stutgart
Train  08:50 - 10::40  01:50 h  HBF Stufftgart - München HBF  Deutsche Bahn   ICE 3456  ECO 34 €
Walk  10:50 - 10:55  00:05 h  München HBF - München ZOB Stadtbus          
Bus    11:03 - 11:28  00:25 h  München ZOB - München Stachus Stadtbus         Linie 11    ECO   4€
Arrive 11:28                           Meeting with xxxxx

To ease the display of different fomats, we can just build a "Description"-string that concatenates all information that folllows the "Duration" and then add "Price as last column, so that the Description string could have fioxed length and line breaks

**Comment by davidtran** [comment]
@GrosR I have talked with Sascha and we can't get timing (arrival, departure) for all trips because it will create too many requests to the third party API.

We can only get the timing in the booking page, because at that page, we have selected trips thus reduce a number of requests we need to call.

**Comment by GrosR** [comment]
Hi Nam, I understand what you say... but it is not what we see..if you click on alternatives of any of the routes delivered in the itinerary screen, you see all departures and arrivals for each alternative for flight and train.. 
For walking segments, I assume that we know the distance in km, so we can calculate departure and arrival, assuming that the average walk speed is 3km/ hour.
For Car, we probably get detailed data from google.

So..what is missing?

**Comment by davidtran** [comment]
We can use google matrix api to calculate duration, just like we did with the homepage. But the amount of API calls will be huge. For example, we have 3 itineraries, each itinerary, we have 5 available trips. Each trip, we have 4 car/bus/train segments.

We have to make 4 * 5 * 3 = 60 requests to google matrix api to get travel time at the trip selection page. I think it's not efficient. 

Google also has a limit on the api: https://developers.google.com/maps/documentation/distance-matrix/usage-limits

**Comment by davidtran** [comment]
since we don't have hotel price at this moment, I think we can remove "other cost" at the route summary.

**Comment by GrosR** [comment]
ok, so we have to limit the display in the itinerary selection to cost and timing information for airplane and train. 
If we can´t deliver departure and arrival for the major segments, the information is useless at all, as nobody will choose a route without knowing when the major segments depart and arrive. 

What is the best approach that we can deliver?

**Comment by davidtran** [comment]
We can show those information at the booking screen.

**Comment by davidtran** [comment]
I will update the the trip engine to show flight number.

**Comment by GrosR** [comment]
ok, fine..let´s do it like that for the 1st release. Once we have Subscribing users, we can improve this as a Subscription feature

**Comment by davidtran** [comment]
Updated. Now we have flight number in route details. I have deployed at here: http://app.1clicktrips.com/

Now I am continue on getting more details for the booking page.

**Comment by GrosR** [comment]
cool... I am going to take a look, soon

**Comment by damianmartone** [comment]
<img width="1215" alt="screen shot 2016-10-06 at 15 28 13" src="https://cloud.githubusercontent.com/assets/8942032/19154135/89bbc066-8bd9-11e6-9c01-74acb27c81b5.png">

dont forget to replace the part under the widget with actual information xD
