### ISSUE TITLE
new icons to support current scenarios implemented 

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#150]
In the route cards, we get bus and taxi suggestions, too .. might be we get AirBnB and Uber, too..this is delivered by Rome2Rio. 

To make the visuals in the route cards complete, we need icons for 
-  bus, taxi, hotel or overnight

in the book & go section, we need icons fopr 

Send mail
print
Export .ics to Outlook
Export .ics to Google Calendar

**Comment by damianmartone** [comment]
@GrosR is the overnight icon an icon that means they stay in that city but without any accommodation selected or what?

**Comment by damianmartone** [comment]
also I think the book & go has enough icons as it is, id leave those four sections without iconography, just as call to action links

**Comment by GrosR** [comment]
the overnight icon shall say, that the trip requires an overnight at this point. 
So if you have trip that starts the day before an appointment and the return trip requires another overnight, the trip would contain two overnights - if the user has selected a hotel or not. 

It is just to show the user how the trip in total will be combined

**Comment by GrosR** [comment]
with the links in the book & go section, i personally find it very unattractive to have a list of links on the left side which cover a lot of space. But let me see how you design it

**Comment by damianmartone** [comment]
Ok so @davidtran can find all the icons already on the 1clicktrips-templates repo

![icon-bus](https://cloud.githubusercontent.com/assets/8942032/18833778/acbcf006-83f2-11e6-83d2-81bb185f2bab.png)

![icon-hotel](https://cloud.githubusercontent.com/assets/8942032/18833780/acbf26b4-83f2-11e6-8731-1decff04dc27.png)

![icon-nights](https://cloud.githubusercontent.com/assets/8942032/18833779/acbef6d0-83f2-11e6-8741-10ecb597f3d4.png)

![icon-taxi](https://cloud.githubusercontent.com/assets/8942032/18833781/acc1e8d6-83f2-11e6-8d64-42f6dc450f1f.png)

For the bus/taxi/hotel theres also all the states (inverted, checked, etc) for all the states in the itinerary. If you can't create the sass styles for them -just copy/paste and replace the plane for taxi for example- let me know and I can do it.

@GrosR the links on the left side are just under the calendar and basically respond to actions for that day. I think it looks a bit more elegant like this, we'll already have too many icons on the other side

<img width="330" alt="screen shot 2016-09-26 at 14 09 54" src="https://cloud.githubusercontent.com/assets/8942032/18833842/fbe81b24-83f2-11e6-8aad-3e5a1e7de035.png">

**Comment by damianmartone** [comment]
would just write "Export to Google Calendar" "Export to Outlook"

**Comment by GrosR** [comment]
and you would also export all ? Or would you ask the user to select either all or "just this"?

**Comment by damianmartone** [comment]
each day, since its tidier but we could have a 'export everything' at the end

**Comment by GrosR** [comment]
ok, fine for me...

**Comment by GrosR** [comment]
I received a trip withou description and symbol.. what is this? 
![image](https://cloud.githubusercontent.com/assets/11087531/18948615/18240cca-8638-11e6-8737-a4e38a7e7858.png)

I received this fpr the trip EFEXCON AG, Zug -> 03.10. 09:00 - 11:00 IOZ Sursee, Switzerland

**Comment by damianmartone** [comment]
i wouldnt place maps inside these cards, complexity grows and the idea its that is an overview, all detailed info comes as a link, so walking icon is ok, ill make it

**Comment by GrosR** [comment]
I discussed the topic today with Nam and I agree, we should keep the booking screen undistracted from other information, also from walking or evtl. other "NON bookables". 
The "bookables" still need timing information, as the user jumps to another platform and must preset the right starting time.

If you look at our printout today, it does not help the user too much. The printout should be the place, where we display the full routing information with start - walk - take train etc. with the relevant timings..

If we would have a smartphone app, yet, it would be better to deliver the route map in the app instead on a printout ...or on top of a printout. 

in the printout, we could display a map

**Comment by davidtran** [comment]
@damianmartone The walking icon still missing.

**Comment by damianmartone** [comment]
sorry @davidtran its now up on the templates
![icon-walk](https://cloud.githubusercontent.com/assets/8942032/19419093/8adf4e3c-93d0-11e6-9522-6ccac0406e9d.png)
