### ISSUE TITLE
Delete itinerary from list

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#152]
When deleting a itinerary, we should ask user if he want to update destination of previous itinerary and origin of next itinerary.

Also. We should update return flight if the last itinerary is deleted

**Comment by davidtran** [comment]
@GrosR I have deployed, you can test. The confirmed dialog for return trip will be implemented in #151

**Comment by GrosR** [comment]
I tried to delete a trip and it throws an error
![image](https://cloud.githubusercontent.com/assets/11087531/18948202/6aa24b6c-8636-11e6-884f-15546a73f73d.png)

**Comment by GrosR** [comment]
I tried to delete a trip, that sterted with 
30.09., 9:00 - 11:00 EFEXCON AG, Zug, Switzerland -> BAUWERK GmbH, Milchstraße, Isernhagen, Germany
30.09. 14:20 - 16:20; Bauwerk GmbH -> Solina Spiez, Stockhornstrasse, Spiez, Switzerland
01.10. 09:40 - Solina Spiez -> Cognition Agency, Dormer Place, Leamington Spa, United Kingdom
Save and start search (Return flight added)

-> "No result"

I tried another sequence and deleted the trip to Cognition Agency .. and the delete threw an error... (I lost the screenshot. 

I tried to delete another one, this worked. 

There seem to be troubles, still, with exception handling and the changes to set the changed origin of affected appointments

**Comment by davidtran** [comment]
I have tried with your trips:
30.09., 9:00 - 11:00 EFEXCON AG, Zug, Switzerland -> BAUWERK GmbH,
Milchstraße, Isernhagen, Germany
30.09. 14:20 - 16:20; Bauwerk GmbH -> Solina Spiez, Stockhornstrasse,
Spiez, Switzerland
01.10. 09:40 - Solina Spiez -> Cognition Agency, Dormer Place, Leamington
Spa, United Kingdom
Save and start search (Return flight added)

It doesn't work because it can't find a trip from *EFEXCON AG, Zug,
Switzerland* -> *BAUWERK GmbH, Milchstraße, Isernhagen, Germany*
it also can't find trip for the return flight.

2016-09-29 16:27 GMT+07:00 GrosR <notifications@github.com>:
