### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#154]
@GrosR you can provide the translation file as a spreadsheet and I will convert it to translation table.

**Comment by davidtran** [comment]
@GrosR  Do you want to have a language switcher ?

**Comment by GrosR** [comment]
yes..once we have translations, we should add a language switcher... I haven´t found the time to translate anything, yet... too many things to do in paralllel...but I´ll do..

**Comment by swapzone** [comment]
I can also do the translations, if it is German :)

**Comment by GrosR** [comment]
@swapzone if you have the time to....I am happy with this!

**Comment by swapzone** [comment]
Sure.
@davidtran where is the language file in the project?

**Comment by GrosR** [comment]
cool!

**Comment by davidtran** [comment]
I can do the translation, if it is American 💣 💣

**Comment by davidtran** [comment]
@swapzone I will push language file soon.

**Comment by GrosR** [comment]
:-) yes, we can add a special translation for Americans, that adds "awsome" or "fantastic" to every item --- and you can dd your Vietnamese "like you" literals, too
