### ISSUE TITLE
itinerary selection - No appointment card - Return trip selection causes error

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#155]
I created a trip
EFEXCON AG, Zug - > Apple near Loomis, CA with a 3 days pause between the next trip. 

In the "No appointment card", I selected "Return trip" card. 

1) The text in the return trip card says: "Return to to EFEXCON AG, Zug, Switzerland" -> there is a "double" to in the phrase

2) The system throws an error "Can not update trip
![image](https://cloud.githubusercontent.com/assets/11087531/18828374/e00ce42c-83d7-11e6-8890-24df0511ee03.png)

**Comment by davidtran** [comment]
I have tested and it works well.
It shows a popup because it can not find a trip to go back to EFEXCON AG.
You can try again with another return locations.
I will remove the "to"

**Comment by GrosR** [comment]
but why doesn´t it find the way back to EFEXCON.. I selected this as starting location in the search screen and there, the destination was resolved properly....else, it would not even have accepted the "save" of the appointment card
