### ISSUE TITLE
Search animation needs some more interaction

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#158]
The popup that shows that we are searching the trips is boaring at the moment.... we should add some more information and fun to it. 

We should enhance the animation with a timer logic that checks, if the user is wating for a longer time already....so we should per default tell the user what we do, like 
- fetching data from a lot of sources...
- filtering the best options for you
- eliminate crap and too expensive offers... 
etc....

on top, if the user has to wait longer, we can add some fun messages like, 
- we are really still working on your job...
- just to bridge waiting time.. do you know about ...
etc...

**Comment by davidtran** [comment]
So I will replace "searching" with dynamic messages ? I think we should not place any message on the top, it would be too distracting..

Here is list of messages I will use, let me know if you want to change
- Fetching data from a lot of sources.
- Filtering the best options for you.
- Eliminate crap and too expensive offers.
- We are really still working on your job.
- Just to bridge waiting time...

Each message will have 2 sec before it is replaced by another message.

![screen shot 2016-10-14 at 10 55 15 am](https://cloud.githubusercontent.com/assets/1154740/19375283/b4874260-91fc-11e6-8f0e-9e2019f0b328.png)

**Comment by GrosR** [comment]
Yes, let us start with this ... but please implement it multilingual and in a way, that makes changes to text easy.
As we enhance and change services over time, this should be easy to maintain
