### ISSUE TITLE
Replace SVG waiting animation with GIF

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#160]
Current animation doesn't work well in old browsers

**Comment by GrosR** [comment]
yes.. I don´t think it must be very "fancy" -- it would already be helpful if we would display some information in the box to help the user to forget, that he´s waiting

**Comment by GrosR** [comment]
I´ll close this issue here and will open a new one in the ideas section with a more detailed description for an improved user experience
