### ISSUE TITLE
book & go screen - time information is missing for all but flights

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#161]
in the resultset, only flights show timing information. The other information for train and other things do not make sense without timing information

**Comment by davidtran** [comment]
It happens because the search engine doesn't return timing for those trip.

**Comment by GrosR** [comment]
can you check with Sascha, why this is the case... if i check the data with Rome2Rio, they have timing information... and as we get data from them, I assume it is a bug in the trip engine or the API

**Comment by swapzone** [comment]
@davidtran did you only search for the big trip segments or did you also retrieve the details?

**Comment by davidtran** [comment]
@swapzone @GrosR I have updated the booking page, now when you go to booking page, it will fetch details and show timing for remaining segments.

**Comment by GrosR** [comment]
cool..going to test it
