### ISSUE TITLE
add trip details from trip detaisl API to route cards and book and go screen

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#167]
trip information must be enhanced by detailed provider and transport information to always show 
- departure time, eg. 17:23 h
- arrival time eg. 18:59 h
- duration. e..g. 1:36 h
- provider, e.g. AirBerlin
- transport id, eg. AB3369

**Comment by davidtran** [comment]
I have added the timing in #161 . We should close this issue.
