### ISSUE TITLE
Trip Engine proposal is far from being good

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#170]
Hi Sascha, 
ich habe mit 1ClickTrips einen Trip gesucht, der einen Rückflug nach PMI nach einem Meeting in Gummersbach liefern sollte. Das Meeting endet am 13.10. umd 15:00 Uhr. 

1ClickTrips schlägt folgendes vor;

![image](https://cloud.githubusercontent.com/assets/11087531/19203077/bbc7db42-8cd5-11e6-9dea-c80d262a0f31.png)

Lt. unserer Engine gibt es nur den Flug über  Dortmund mit mehreren umstiegen. 

Von Gummersbach fliegt man aber viel geschickter über Köln und dort gibt es auch Direktflüge, die günstiger sind: 
![image](https://cloud.githubusercontent.com/assets/11087531/19203170/17c673c2-8cd6-11e6-8440-2cf0682c2e91.png)

Auch die Bahnstrecke passt vom Timing: 
![image](https://cloud.githubusercontent.com/assets/11087531/19203195/3424c384-8cd6-11e6-9a4a-0e3e7f5cec93.png)

Kannst Du nachvollziehen, was unsere Engine da rechnet?

**Comment by swapzone** [comment]
Hi Rue, liefert Rome2Rio die Option über Köln?

**Comment by GrosR** [comment]
ja, Rome2Rio zeigt CGN-PMI als erste und beste Strecke von Gummersbach nach PMI ist

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Sascha Gros <notifications@github.com>
Gesendet: Freitag, 7. Oktober 2016 22:39:02
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Author
Betreff: Re: [clowdfish/ttg-frontend] Trip Engine proposal is far from being good (#170)

Hi Rue, liefert Rome2Rio die Option über Köln?

-

**Comment by swapzone** [comment]
Nach 3 Stunden Debugging habe ich das Problem gefunden: Wenn ich zwei majorSegments in einer Route habe, darf ich die nicht gleichzeitig mit echten Zeiten anreichern. Bisher lief es so, dass ich erst die Flüge suche und dann per Heuristik feststelle, welcher Flug der beste sein könnte. Auf diesen Flug habe ich dann die großen Zugsegmente hin optimiert. Die passen dann aber überhaupt nicht zu anderen Flügen. Und im schlimmsten Fall passt die Heuristik nicht, dann startet der Zug sogar vor Meeting Ende und damit wird die ganze Route rausgefiltert. Jetzt werden nur noch Flugsegmente angereichert und erst wenn man sich die Details holt (was Nam bisher noch nicht implementiert hatte), werden die restlichen Segmente angereichert.

Die neue Version liegt im Repository, Nam muss nur noch das Paket auf dem Server aktualisieren (ttg-search).

**Comment by swapzone** [comment]
@davidtran please update the ttg-search package on the server. I made some changes and changed the version number already. And do not forget to restart the whole Node process :)

**Comment by GrosR** [comment]
Subbe .. vielen Dank.. dann muss Nam ran..:-) und dann ich zum testen

Rüdiger Gros
+41 44 586 5018
www.efexcon.com<http://www.efexcon.com>
EFEXCON AG.
Digitale Transformation durch Cloud, Business Software und Software Engineering.
Ihr Partner für SharePoint, Office 365, Azure, Dynamics CRM

________________________________

**Comment by davidtran** [comment]
👍  I have updated the search engine on server

**Comment by GrosR** [comment]
cool...I´ll test

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Montag, 10. Oktober 2016 09:51:12
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Author
Betreff: Re: [clowdfish/ttg-frontend] Trip Engine proposal is far from being good (#170)


?? I have updated the search engine on server

-
