### ISSUE TITLE
book & Go screen - Font Size and more

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#171]
I think the font for teh headings is too big, we should try with 12 px

The .ICS Exprters are still missing .. 

- Damian wanted to deliver improved templates

- Who is working in the .ics exprters?

**Comment by swapzone** [comment]
@davidtran same issue like the others I commented on. Take the ics creation code from an older version.

**Comment by damianmartone** [comment]
Yes im taking care today of https://github.com/clowdfish/ttg-frontend/issues/148 because I hadn't had time so far. So all is left is the ics exporters.

**Comment by GrosR** [comment]
ok, thanks... I was not aware who is taking "the ball" for this issue

**Comment by davidtran** [comment]
@GrosR @swapzone We need to update the API because the old API is supposed to handle only generate 1 trip plan per request. But now we have many appointments, the trip plan api should accept an array of search object.

**Comment by davidtran** [comment]
I created an issue at here: https://github.com/clowdfish/ttg-search/issues/90
