### ISSUE TITLE
Current UX and Design is not usable on mobiles

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#172]
The current design is not usable on mobile screens. 

The start page is acceptable if you turn the mobile to horizontal mode . but the keyboard of the mobile overlaps everything and it is hard to navigate then, especially with calendar and time controls. 

In vertical mode, the data entry fields must switch to a single column mode - in two column mode, you can hardly see the fields at all on an iPhone 4 or 5.

In the itinerary screen, it is even harder: 
- the left pane covers the full screen and you don´ßt know, what your are looking at, if you don´t know the workflow already. The correspnding routes to the active appointment are not visible at all...so you must scroll down the screen until all appointments in the left pane are passed - then you see the routes ... but it is hard to understand what this has got to do with the active appointment. 

I think we should take a look together to discuss possible options.

**Comment by damianmartone** [comment]
I think with all the changes some stuff might have slipped but its minor,
for the start page its only about adding some different xs classes, and cut the text of the "save and add new appointment" to "save and add new" or its too long.
ive fixed on the templates repo

<img width="368" alt="screen shot 2016-10-10 at 11 31 26" src="https://cloud.githubusercontent.com/assets/8942032/19231945/32f6cb20-8edd-11e6-8f77-20777b58bd5d.png">

Regarding the itinerary screen, the sidebar should not be shown there on mobile, we can think if you want of a normal progress bar, but we cant show that much info in a phone, so we'll just show the contents of the main div

![screen shot 2016-10-10 at 11 41 04](https://cloud.githubusercontent.com/assets/8942032/19232145/743c491a-8ede-11e6-87e5-185b858e1e9e.png)

I can add the design for this but then i'd need @davidtran to use js to calculate how many elements (Appointments) are there and divide the elements inside the progress bar so that it works.

**Comment by davidtran** [comment]
Cool, I will checkout the templates and update to our app.

**Comment by damianmartone** [comment]
ok but progress bar is not yet done, still need the ok from @GrosR if he thinks its the right solution ill build it quickly, for now at least hiding the appointment list on mobile is the smart thing to do

**Comment by GrosR** [comment]
yes, makes sense to go this way... it would also be helpful to have the route cards displayed with more compact information, so that you can see 3 routes on a single screen without scrolling, 
Any idea on how to reduce the space used? 
I think we could limit the information to Total Price, Total time,  #Changes Departure time. We can also display price without decimals, time as hh:mm

**Comment by damianmartone** [comment]
<img width="390" alt="screen shot 2016-10-10 at 20 59 08" src="https://cloud.githubusercontent.com/assets/8942032/19247671/94b6f520-8f2c-11e6-978d-05fab14ad7b8.png">

@davidtran i finished the bar and step count on the templates, ill see if I can reduce the content, but at least for the sidebar part we should just display active appointment on mobile.

**Comment by damianmartone** [comment]
@GrosR this is the smallest i could take the information without doing a lot of work changing into a mobile structure, 2.8 cards show on a scroll on an iphone 6

<img width="398" alt="screen shot 2016-10-10 at 21 16 43" src="https://cloud.githubusercontent.com/assets/8942032/19248207/f0a837e8-8f2e-11e6-9e68-49906ffe1272.png">

**Comment by GrosR** [comment]
looks good... makes it aso clear that there might be more Cards when Scrolling. 
Let^s go for this

**Comment by davidtran** [comment]
👍

**Comment by davidtran** [comment]
I have updated our website for this issue, please review.

**Comment by GrosR** [comment]
Better than before, but we have still some issues: 
- the "Save and Add New"-Button overlaps the "clear Card" button - it needs to much space - tested on an IPhone 5) => we should reduce the text to "Add New" and change the text on the search button below to "Save and Search"
- on the itinerary screen, we must remove the complete header with logo etc., so that the screen starts with the progress bar. Below the progress bar, the minimu appointment info like in the screen design of Damian shall be displayed 
- the progress bar starts with the 1st appointment selected already, so we must only show results for this appointment - all info from the left bar must be hidden. 
- the progress bar should keep sticky on top of the screen, even if a user scrolls. if the user selects a route and clicks next, the progress bar goes to the next itinerary and shows the minimum appointment info like in Damians screen and the route options for this appointment
- the appointment description must not show the text "select your preferred travel route and click "Next" etc.. this takes to much space. The fonts must be smaller, like in the design of Damians screen samples. 
We should also check, if we can shorten the destination text: 
I have e.g. this text fpr the return flight to Palma: "Return to Palma Mallorca Airport, Palma, Spain, Palma Mallorca Airport".   It should be sth. like "Return to Palma de Mallorca"

**Comment by davidtran** [comment]
We should hide the left section ?
![screen shot 2016-10-13 at 2 43 00 ch](https://cloud.githubusercontent.com/assets/1154740/19340498/60d2fa00-9153-11e6-8342-2b3b9ad58841.png)

**Comment by GrosR** [comment]
Yes...please take a look at Damian's screen. The progress bar on top represents the left pane. Each segment of the progress bar is one appointment.
Once a segment is active, display the corresponding minimal appointment info directly below the progress bar, like on Damian's screen.
The rest of the screen is reserved for route alternatives, as this is the info which is most relevant in this step.
If the user clicks next, proceed the progress bar to the next appointment

**Comment by damianmartone** [comment]
ok ill have tomorrow to work on this, will respond properly and make the necessary changes.

**Comment by GrosR** [comment]
Fine.. didn't know that you have to change sth, I thought that Nam had a coding issue

**Comment by davidtran** [comment]
I am working on this issue too. I have finished from 1st to 4th item  in Rudiger comment.

**Comment by davidtran** [comment]
Just updated our website again.

**Comment by davidtran** [comment]
I think we should reduce the action section. It takes too much space on mobile.
![screen shot 2016-10-13 at 11 26 48 ch](https://cloud.githubusercontent.com/assets/1154740/19357601/948f488c-919c-11e6-9bce-f641364671c0.png)

**Comment by GrosR** [comment]
Hi Nam, I agree, we must get rid of - reduce or restyle several things for the mobile. I tested your latest deployment, which has several improvements (good!)  - but there are still several issues. I will create new tickets for the issues found to make it easier to manage tracking and closing of individual tickets.

To answer just you comment on cleaning up the book & go section:
Ideally, we would have a "Hamburger menue" in the upper right corner, where we can put the links in - so that they are away from the screen - but still reachable. 

We should also reduce the Size of the Calendar date. I think it should have the same height as the Appoiintment header. 
The font for the details should be reduced to a much smaller font.
