### ISSUE TITLE
itinerary selection - endless loop after appointmentment change in "trip not found" card

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#173]
I entered two appointments 
1. PMI-> Marquardt Service GmbH, 12.10. 9-16:30 Uhr
2. Marquardt Service GmbH -> xappido Geuensee, 13.19. 10-12 Uhr 

@swapzone At first, the 2. trip was shown as "route not found" card -> This must be a bug i the trip engine, as it would be easy to either take the car or train. in both cases, an overnight would have been necessary. -> I think that all distances < 500 km should be reachable by car / rental car... do you have an idea, why this is not delivered as trip option? 

@davidtran Still, apart from the wrong trip not found result. I clicked on the link to change the appointment and changed the appointment to start 2 hours later. 

The system went into an endless loop: 
![image](https://cloud.githubusercontent.com/assets/11087531/19249119/0a76c4fa-8f34-11e6-86ce-6b0b18de346f.png)

**Comment by swapzone** [comment]
See issue #174 for explanation (regarding the trip engine).

**Comment by davidtran** [comment]
I am fixing this issue.

**Comment by davidtran** [comment]
Fixed.

You can test with this route:
San Francisco, CA, United States -> ASDADFAS, Thiruvaniyoor, Kerala, India 
ASDADFAS, Thiruvaniyoor, Kerala, India -> New York, NY, United States
