### ISSUE TITLE
Trip engine does not find simple trips

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#174]
@swapzone Hi Sascha, I tried some samples with simple trips, where 1ClickTrips display "no trips found"

![image](https://cloud.githubusercontent.com/assets/11087531/19249443/e68b3b96-8f35-11e6-8c45-050ebbc5b740.png)

whereas Rome2Rio shows sensible options. 

![image](https://cloud.githubusercontent.com/assets/11087531/19249459/f90bd58c-8f35-11e6-9335-9d7df6fb997f.png)

Any idea what happens here? I have the impression that the old engine was more reliable then the current one..I would like to kmow, if the results get lost on the way, in the heuristics, in the API or in the frontend?

**Comment by swapzone** [comment]
There is no old engine and new engine. The engine evolved over time so even if I wanted to, I could not go back to a "perfect" old version. However I fixed that issue. It consisted of two issues:
- the trip engine filtered out the public transport alternative, because it takes too long (almost 3 times as long as the other two alternatives). I now said, that it should not filter out any trip that takes less than 2,5 hours.
- it then filtered out the car and taxi trip because I calculated it to arrive exactly on time, but then filtered on: are you arriving before the meeting :) So now it's not filtered out anymore.

**Comment by swapzone** [comment]
If something is wrong with the trip engine, it would be good to add all bugs here: https://github.com/clowdfish/ttg-search/issues 
Then I can reference it in my commit.

**Comment by swapzone** [comment]
@davidtran can you please update the ttg-search package on the server? I changed the package number.

**Comment by GrosR** [comment]
HI Sascha, 
thanks for the update and the changes in the settings. I have not access to https://github.com/clowdfish/ttg-search/issues at the moment... so you should give me rights to use this site :-)

I also know, that there is no "old" and "new" engine. Still, even with all given restrictions that you removed now, the old engine delivered results reliable. At least, I can´t remember a case, where we did not get any trip. 

I therefor think that we applied some rules or changes in between, that affect the result sets more restrictive than earlier - which you resolved by removing restrictions, that seemed to have worked before. 

I am not sure if we have other not yet identified reasons, as the interaction between backend and frontend is now more complex. 

Basically, the engine should work like that: 
- calculate all possible trips
- segment them in ideal trips, trips starting the day before, trips that arrive too late (but not much)
- the frontend, we should show 
1. the ideal trips, if any are available ..and we could show a link to "day before results, if any are available
2. if no ideal trips are avialble, we could shopw day before trips per default and show a link to trips that are little to late as a link
3. if neither ideal trips nor day before trips are available, we could show, that there are no trips on time, but the link to a little too late
4. if we find nothing at all, car should be the last fallback

I don´t know, if the engine keeps "not ideal trips" at all, at the moment .. and it is possible, that the above algorithm would cost to many requests or time, but in theory, the cascade probably reflects how users would expect to be informed

**Comment by swapzone** [comment]
What the engine does:
- create all possible trips
- find concrete schedules for major segments
- filter out those trips that arrive too late / leave too early (even though we do not yet have the timings for the minor segments, so we just predict it by segment and transfer duration)

That is what the search engine was designed for. We changed some heuristics for filter out particular alternatives and of course we must fine-tune that part. That's what we are doing currently.

**Comment by swapzone** [comment]
Actually you should have access to https://github.com/clowdfish/ttg-search/.
Can you see the files?

**Comment by GrosR** [comment]
yes..now I can see the files.. :-) It is easier now to add items without the need to hack the permissions :-)
