### ISSUE TITLE
date picker bug 

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#175]
if you choose the 10.04.**2017** as Start, End 29.04.2017 the screen takes day and month over, but not year. (tested on: Mac OS Sierra / Safari )
The result creates an error message, that tells you that the date can´t be earlier then the current date.

![image](https://cloud.githubusercontent.com/assets/11087531/19271386/c9c53680-8fc4-11e6-8899-9b49dac34780.png)

on the iPad, it behaves even worse and stacks up invalid  appointments

**Comment by davidtran** [comment]
Hi @GrosR ,
Turn out it is (a bug from jQueryUI)[https://bugs.jqueryui.com/ticket/7759] and they won't fix it. 

If I discard the "year" in date format. The year number will not be updated correctly when selecting date. 

So in order to maintain the year number, I have to use this format: "dd.mm.yy" => day, month, year. 

There is no workaround for this bug so I will look for another datepicker library.

**Comment by GrosR** [comment]
Isn' t that depending on language settings?

It would be ok to have YY instead of YYYY, but dd .mm.yy works only in Europe.. in the US, it would be a problem

**Comment by davidtran** [comment]
"yy" still shows full years, like 2016

**Comment by davidtran** [comment]
for US we display it as: years-month-day ?

**Comment by GrosR** [comment]
for us, they use mm/dd/yyyy

**Comment by GrosR** [comment]
how can I test this?

**Comment by davidtran** [comment]
Because we don't have a language switcher now. You can test by open the Chrome Inspector:
- Right click on website
- Click on Inspect
- Go to console tab in the inspector
- Paste: angular.element('*[ng-app]').injector().get('$translate').use('de') and press enter
- Date format will be changed

**Comment by GrosR** [comment]
thanks

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Donnerstag, 20. Oktober 2016 05:09:40
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Mention
Betreff: Re: [clowdfish/ttg-frontend] date picker bug (#175)


Because we don't have a language switcher now. You can test by open the Chrome Inspector:

  *   Right click on website
  *   Click on Inspect
  *   Go to console tab in the inspector
  *   Paste: angular.element('*[ng-app]').injector().get('$translate').use('de') and press enter
  *   Date format will be changed

-
