### ISSUE TITLE
Mobile Issue - remove header of book & go page

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#179]
The website header can be removed on the mobile or at least be cleaned up:
The icons fopr mail and print can be removed - they should be replaced by the links moved to the "Hamburger menue" - see Issue #172 

The Header text must be changed, even for the website: the current text claims, that the user can store trips - which they acutally can't at the moment. 

The text should therefore be:
Header: Your itinerary with bookable items

**Comment by davidtran** [comment]
@GrosR 
I created a hamburger menu for booking page
![screen shot 2016-11-04 at 12 30 59 ch](https://cloud.githubusercontent.com/assets/1154740/19995521/969fc472-a28a-11e6-8a3e-36d13f86e441.png)
![screen shot 2016-11-04 at 12 31 04 ch](https://cloud.githubusercontent.com/assets/1154740/19995523/96f877ca-a28a-11e6-9978-e87d4337b461.png)

**Comment by GrosR** [comment]
cool

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Freitag, 4. November 2016 06:31:34
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Mention
Betreff: Re: [clowdfish/ttg-frontend] Mobile Issue - remove header of book & go page (#179)


@GrosR<https://github.com/GrosR>
I created a hamburger menu for booking page
[screen shot 2016-11-04 at 12 30 59 ch]<https://cloud.githubusercontent.com/assets/1154740/19995521/969fc472-a28a-11e6-8a3e-36d13f86e441.png>
[screen shot 2016-11-04 at 12 31 04 ch]<https://cloud.githubusercontent.com/assets/1154740/19995523/96f877ca-a28a-11e6-9978-e87d4337b461.png>

-
