### ISSUE TITLE
Send email

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#18]
When click on email button at the bookings screen, it opens a email editor (gmail/outlook) and attach the image of booking screen

**Comment by GrosR** [comment]
See Issue #74

**Comment by davidtran** [comment]
this task should be implemented in the backend.

**Comment by GrosR** [comment]
ok

**Comment by swapzone** [comment]
@davidtran why and how should that implemented in the backend? In my opinion it's a frontend task: Open an email with the content given in HTML. An image of the booking screen doesn't make any sense, because it would not be readable on smaller screens.
