### ISSUE TITLE
Hotel booking links are displayed - but do nothing

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#181]
The Hotel booking links do nothing at the moment  - I am not aware if this is a bug or an not yet implemented behavior

**Comment by davidtran** [comment]
It is not implemented. The backend doesn't provide link and the overnight segment is generated from frontend. So we must implement from frontend.

**Comment by GrosR** [comment]
Ok, understand... I think it would be good to have the link creation as backend API available.. so that Any frontend we are going toprovife can use it

**Comment by davidtran** [comment]
OK

**Comment by davidtran** [comment]
Expedia appears to be a better option since their search api can search by longitude and latitude. You can register an account at here. https://www.expedia.com/p/network-affiliate

**Comment by davidtran** [comment]
@GrosR what is our choice with hotel API

**Comment by GrosR** [comment]
I think we need to investigate a bit more about possible APIs at all.


It seems that Expedia delivers one of the best choices - but I don´t know about pricing yet. (http://developer.ean.com/spec/)

https://www.b2btravelgroup.com/faqs/ - this is my neighbor, I´ll talk to him


Travelfusion is another candidate: https://www.travelfusion.com/corporate/page/tf-hotel-api

http://www.software.travel/our-platform/<http://www.software.travel/our-platform/pricing-models>




There are some global Hubs like GPHub, that aggregate EVERYTHING .. but I have to find out about cost and booking options



I checked booking.com and Amoma, where I think that API support is too poor



Here are some more interesting APIS:

http://www.olery.com/blog/the-best-travel-apis-discover-contribute/


http://www.programmableweb.com/news/44-booking-apis-rezgo-tourcms-and-travelport/2012/08/21


http://www.programmableweb.com/category/hotels/apis?category=20057
http://www.programmableweb.com/news/top-10-travel-apis-uber-tripadvisor-and-expedia/analysis/2015/04/24
Top 10 Travel APIs: Uber, TripAdvisor and Expedia ...<http://www.programmableweb.com/news/top-10-travel-apis-uber-tripadvisor-and-expedia/analysis/2015/04/24>
www.programmableweb.com
The APIs that made it to our top 10 travel APIs list offer a wide range of capabilities. Within this list you can find APIs for transportation requests, travel ...







Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Freitag, 4. November 2016 04:22:27
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Mention
Betreff: Re: [clowdfish/ttg-frontend] Hotel booking links are displayed - but do nothing (#181)


@GrosR<https://github.com/GrosR> what is our choice with hotel API

-

**Comment by davidtran** [comment]
We are implementing it in #217
