### ISSUE TITLE
Labels Footer Info and Social Media need content

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#182]
When the web app is loaded, you can shortly see the labels for Footer and Social media flicker on the upper left corner if the screen, before the search form is loaded. 

This should be filled with content...

On the mobile, these labels are shown, too - and content is missing, too - on mobile, we could even skip this info.

**Comment by davidtran** [comment]
Well, how should I fill the content ?

**Comment by GrosR** [comment]
I think we should Add corporate information and logo on the left, menu links in the middle and tweets on the right for the web.. on mobile. We can just add logo and a home-link
