### ISSUE TITLE
Mobile book & Go Screen - Home-Navigation not clear

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#183]
if you are on the book & go screen on the mobile, it is not clear how one can get back to the search screen. 
As the Logo is missing compared to the web-screen, I suggest that we offer a "Hamburger menue" on top, where we hide the Home and Action Links

**Comment by davidtran** [comment]
We should keep our logo at every screen, so user acknowledges that they are using our website. When we go from search screen to trip screen, the logo is lost, user might be confused because he doesn't know if he still stays on 1ClickTrips or not.

**Comment by GrosR** [comment]
I think we should have the logo on the footer, printout, generated ics-files and when we jump to other sites.

I think it is too big and takes to much space on small screens on top, don't you?

I think that 'color-branding' through the sites is better... and once the footer is generated well, we see the logo their... how about this?

**Comment by davidtran** [comment]
I think the logo is more consistent. We can make the logo smaller.

**Comment by GrosR** [comment]
Let's give the small logo  a try:-)
