### ISSUE TITLE
Mobile start screen - header part takes to much space

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#184]
The header above the form (Logo, Menue, Team) including the the Slogan "Booking Business trip made easy" don^t add value on the mobile. we should remove this. 

To not loose all information, we can add the menue links and the logo into the footer. 

The only thing that we need is the descriptive header above the search form:
Enter your appointment data. Get the perfect door-to-door itinerary.

**Comment by damianmartone** [comment]
ok I guess @davidtran can take this without me pushing anything since its just a responsive thing

**Comment by GrosR** [comment]
Yea, just wanted your opinion

Rüdiger Gros
+41 44 586 5018
www.efexcon.com<http://www.efexcon.com>
EFEXCON AG.
Digitale Transformation durch Cloud, Business Software und Software Engineering.
Ihr Partner für SharePoint, Office 365, Azure, Dynamics CRM

________________________________

**Comment by damianmartone** [comment]
👍
