### ISSUE TITLE
Mobile Screens - Search Page - Calendar display - Keyboard and Buttons

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#185]
Hi Damian, hi Nam, 
in the current version, the calendar (which is great in the web) is difficult to handle on the small screen, as it displays 2 month and eben 1 month is difficult to handle, as the keyboard covers half the screen. 

Is it possible to let the keyboard diappear when the calendar is displayed? 

A similiar issue comes up with the buttons on the appointment card and the "save & search button. As the form covers a lot of space, the save & search button is out of sight and out of screen when you walk through the form, so an average user will probably not understand how to navigate the form.......because you have to scroll to find the other button to save and search. 

Any idea on how to improve this?

**Comment by davidtran** [comment]
I will looking for solution to hide the keyboard. About the search button, I can stick it to the bottom. How do you think.

**Comment by GrosR** [comment]
Hiding the keyboard is good, but only for the calendar .. and evtl. For time pickers. In the other boxes, we need the keyboard.
Sticking the save and search button to the bottom seems to be a good idea.. let's try it

**Comment by damianmartone** [comment]
great ;)

**Comment by davidtran** [comment]
Look like save and search button to bottom doesn't work so well. The design will not beautiful.
But we can save a lot of space but cutting space and labels and make button smaller. How do you think ?
![screen shot 2016-10-17 at 12 20 49 ch](https://cloud.githubusercontent.com/assets/1154740/19426137/4da60f76-9464-11e6-9cda-7e02f3605969.png)

**Comment by GrosR** [comment]
Let's try this

**Comment by damianmartone** [comment]
usability wise is not good to skip labels but as you wish

**Comment by GrosR** [comment]
@damianmartone so you have a better proposal?

**Comment by davidtran** [comment]
I have just deployed our website.

![screen shot 2016-10-17 at 5 03 51 ch](https://cloud.githubusercontent.com/assets/1154740/19433640/bc88ea90-948b-11e6-994d-389974d71d20.png)

**Comment by davidtran** [comment]
I think we need an icon for start and end time.

**Comment by GrosR** [comment]
or labels...
