### ISSUE TITLE
Mobile-Calendar should only show 1 month

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#189]
on the mobile device, the calendar should only display one month - on the web, the 2 month view is good

**Comment by GrosR** [comment]
HI Nam, I don´t see any change..it is displayed still with 2 month .. did you fix anything already?

**Comment by davidtran** [comment]
Yes, I forgot to pull it on production. You can test now.

**Comment by GrosR** [comment]
will check it

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Donnerstag, 20. Oktober 2016 05:07:46
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Author
Betreff: Re: [clowdfish/ttg-frontend] Mobile-Calendar should only show 1 month (#189)


Yes, I forgot to pull it on production. You can test now.

-
