### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#19]
We can use webpack to increase the build time of our website. With webpack, our app is easier to maintain. I will use branch "webpack-experiment" for this task.

**Comment by davidtran** [comment]
almost done. @swapzone you can test now:
install typings and npm packages.
**Commands:**
npm start: run website in development mode
npm build: build all files and copy to dist folder

I will update test command soon.

**Comment by swapzone** [comment]
Let's stick with webpack. I will merge the branch into develop.
