### ISSUE TITLE
Book& Go - Export Outlook calendar items

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#190]
I just tested the ICS-Links in the Book & Go section. 

It opens the authentication dialog and already starts the ics export - as the authentication fails if your currently not logged in into the right account, the systems goes into an endless loop: 

![image](https://cloud.githubusercontent.com/assets/11087531/19961386/ac069670-a1b2-11e6-92e8-a18e453c8d8f.png)

The code should not start to try the export until the authentication is confirmed as "accepted". 

The authentication window does not show the accounts selection - but just a white window. 

It showed my accounts one time - but when I selected the right account for my calendar, it hang up

After a refresh of app.1clicktrips.com , the authentication dialog came up correctly again: 
![image](https://cloud.githubusercontent.com/assets/11087531/19961493/35e95be8-a1b3-11e6-942c-daf725ad8729.png)

After confirming the right account, the authentication dialog gets "white again" and than hangs up.

**Comment by davidtran** [comment]
I have fixed, the spinner will show after user finish authentication.
