### ISSUE TITLE
Book & Go - Export to Google Calendar

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#191]
I exported this itinerary to Google Calendar

![image](https://cloud.githubusercontent.com/assets/11087531/19961627/efa83fae-a1b3-11e6-9966-a8bb0937f570.png)

The itinerary is missing the most important information at all - but I´ll open another ticket for that - but 

According to the itinerary, we should have this in the calendar: 

Travel to appointment at Westnetz GmbH, 7.12.2016, 9:24 - 13:17
Appointment at Westnetz GmbH, 7.12.2016, 15 - 17 Uhr
Return Trip to Palma des Mallorca, 7.12.2016, 19:25 - ´08.12.2016, 07:50

The return trip alternatives itself are all crap ! We need to fix that the search engine, as nobody will take a returnflight with 3 stopvers in the night to bridge a 2 hours direct flight distance., 
If a return trip for short national trips does not arrive the same day, we should add an overnight and fly in the morning - > I´ll create a search engine ticket

Still:
This is what the Google Calendar exporter creates: 

![image](https://cloud.githubusercontent.com/assets/11087531/19961863/3eded104-a1b5-11e6-9b31-56cde85d97d9.png)

Instead of creating 3 items for "Trip to" - "Meeting" - "Return Trip" - it creates 1 item for "Trip to" and forgets the rest

**Comment by davidtran** [comment]
@GrosR 
The export button on each appointment only work with that appointment. If you export a normal appointment, it will create a "Trip to" and "Meeting" event in calendar. If you export a return trip, it will create "Return trip" event in calendar. Do you think it should export all of them, if so I think we need to put the export button the the header, and it won't associate with any appointment.

I just fixed the issue which it only create "Trip to" event and doesn't create "meeting" event.

**Comment by GrosR** [comment]
yes, it fully makes sense to put the export in the header to export everything in a single step with one authentication

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Freitag, 4. November 2016 03:50:17
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Mention
Betreff: Re: [clowdfish/ttg-frontend] Book & Go - Export to Google Calendar (#191)


@GrosR<https://github.com/GrosR>
The export button on each appointment only work with that appointment. If you export a normal appointment, it will create a "Trip to" and "Meeting" event in calendar. If you export a return trip, it will create "Return trip" event in calendar. Do you think it should export all of them, if so I think we need to put the export button the the header, and it won't associate with any appointment.

I just fixed the issue which it only create "Trip to" event and doesn't create "meeting" event.

-

**Comment by davidtran** [comment]
Cool, I will remove "export to outlook" and "export to google" from the sidebar, and move them to the top to align with "print" button.
