### ISSUE TITLE
Itinerary screen - handling of total cost by unknown cost

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#192]
In the itinerary screen, we display ~0 EUR as price mostly for trains - but probably are we simply missing data,. 

We should not display 0 EUR in this case - we should either show a good estimation or we should show , that we don´t have data. 

Typically, Rome2Rio will deliver estimated cost so we should be able to display this

**Comment by davidtran** [comment]
will fix in #176
