### ISSUE TITLE
Book & Go needs more details for trip steps

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#193]
in the current book & go screen, we neither have timings nor transport numbers. 

Most of the book & go information is useless without details, like 

- "take a train from a to B"

at what time? What train? which provider? What train or bus station?

**Comment by davidtran** [comment]
currently, we have these details for a train segment. Are they enough ?

![screen shot 2016-11-04 at 12 33 44 ch](https://cloud.githubusercontent.com/assets/1154740/19995557/0986c436-a28b-11e6-89b7-d11c0a01ce60.png)

**Comment by GrosR** [comment]
a typical train Segment should show the train provider, the train number and Start and destination.


I don´t know if vehicle represents the train number, we should check this with routes we know ourselves.


My understanding of this segment would be translated to:


Take "Bart"-Train #3 from Pittsburg/Bay Point to SFIA/Millbrae



From my perspective, the information about the train station and the location of the train station location  is missing

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Freitag, 4. November 2016 06:34:38
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Author
Betreff: Re: [clowdfish/ttg-frontend] Book & Go needs more details for trip steps (#193)


currently, we have these details for a train segment. Are they enough ?

[screen shot 2016-11-04 at 12 33 44 ch]<https://cloud.githubusercontent.com/assets/1154740/19995557/0986c436-a28b-11e6-89b7-d11c0a01ce60.png>

-

**Comment by davidtran** [comment]
is this route better ? I have added some more information for flight, bus and train segments.

Do you want to replace "Civic Center/UN Plaza to San Francisco" with "Pittsburg/Bay Point to SFIA/Millbrae" ?

![screen shot 2016-11-04 at 10 14 18 ch](https://cloud.githubusercontent.com/assets/1154740/20010805/17eb60da-a2dc-11e6-8fd3-62ab0705f5a5.png)

**Comment by GrosR** [comment]
Hi Nam,


this is already much better - still we should have the start times for each segment, because now, the user has no clue at what time he needs to start or at what time he needs to be at a bus- or train station.


We should be as clear as possible  - so, if "Pittsburg/BayPoint to SFIA/Millbrae" is a better description than "CivicCenter/UN Plaza to San Francisco", than we should use it.   As I have no idea where Pitsburg/Baypoint is or if this is a more precise location than Civic Center, it is not possible to tell if we should replace one by the other -


The most important question you have to answer yourself is: would you find your way and follow our itinerary without doubt and do you have all information you need to get to your next meeting guided by 1ClickTrips?

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Freitag, 4. November 2016 16:16:06
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Author
Betreff: Re: [clowdfish/ttg-frontend] Book & Go needs more details for trip steps (#193)


is this route better ? I have added some more information for flight, bus and train segments.

Do you want to replace "Civic Center/UN Plaza to San Francisco" with "Pittsburg/Bay Point to SFIA/Millbrae" ?

[screen shot 2016-11-04 at 10 14 18 ch]<https://cloud.githubusercontent.com/assets/1154740/20010805/17eb60da-a2dc-11e6-8fd3-62ab0705f5a5.png>

-

**Comment by davidtran** [comment]
The date & time of each segment will be appeared if response from backend have it. I think the current title of train segment is okay. We already have the route info at bottom.. so we need to test with user, if he is okay with these info. We keep it, otherwise, we have to update our segment info.

**Comment by GrosR** [comment]
#193 is ok so far - but if we get timings, we should show the segments like we do with flights - I´ll put the issue back to "To Do" to not forget to add timings

**Comment by davidtran** [comment]
Now we always have timing in bus and train segments. I will close this issue.
