### ISSUE TITLE
Book& Go Screen - don´t show things that don´t work yet

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#194]
We shoudl only show things in production that really work and are tested, so Links like "Send E-Mail", "Print", Export to xxx should be hidden as long as the features are not available

**Comment by davidtran** [comment]
I will hide the email button

**Comment by GrosR** [comment]
ok - once we know exactly what we do with this, we can reactivate it, if we need.


From my perspective, it is much more important to offer social sharing features to let users like or recommend us or share trips with friends and stuff like this


Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Freitag, 4. November 2016 06:34:59
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Author
Betreff: Re: [clowdfish/ttg-frontend] Book& Go Screen - don´t show things that don´t work yet (#194)


I will hide the email button

-

**Comment by davidtran** [comment]
We can create a sharable url like this: https://app.1clicktrips.com/trips/asdkgh

When user go to this page, we can pull trip information from server. But as you said on Skype, we don't need user to share link at this time.

**Comment by GrosR** [comment]
yes, creating "Dropbox-Like" Share-Links makes sense - and we can add several social sharing options on top - once we run stable :-)

Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Freitag, 4. November 2016 07:37:56
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Author
Betreff: Re: [clowdfish/ttg-frontend] Book& Go Screen - don´t show things that don´t work yet (#194)


We can create a sharable url like this: https://app.1clicktrips.com/trips/asdkgh

When user go to this page, we can pull trip information from server. But as you said on Skype, we don't need user to share link at this time.

-
