### ISSUE TITLE
Search-Screen - Date-Validation bug

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#195]
When you enter a meeting date at the same day of an already existing meeting - but where the start and end hour of the new meeting is BEFORE the already existing meeting, the system throws an error and sais, that "Appointment time must be greater other appointments"

**Comment by davidtran** [comment]
Well that is a feature from me :). New appointment should be greater than previous appointments. What do you think ?

**Comment by GrosR** [comment]
I think that it can happen that you enter a meeting - and then find out that you can insert another one the same day before the other meeting due to the other meetings schedule.


I give you an example:

You have a meeting in Zürich at 3 PM. plan that and find out that you still have to take a flight the day before with an overnight - so you´ll be in Zürich anyway.


Now you add 1 or two other meetings in the area of Zürich, starting at 9 AM and 12 AM - both ok, even though your initial meeting is at the same day.


What we have to check is, if another meeting that starts the same day will still allow you to be on time for the already planned meeting, so


if planned meeting was start at 3 PM - and new meeting ends at 1 PM and travel time from new meeting takes too long to arrive on time for the previously planned meeting - we shall display your message :-)



Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Innovation, Software Integration und Custom Solutions für OnPremise, Mobile und Web seit 2005.
Dynamics CRM | SharePoint | Office365 | Azure | IoT | XAMARIN | Sharegate | NINTEX | Theobald Software | BPA Solutions
Automotive | Industry | Production | Energy | LifeScience | Medical | Public Sector | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Samstag, 5. November 2016 07:23:58
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Author
Betreff: Re: [clowdfish/ttg-frontend] Search-Screen - Date-Validation bug (#195)


Well that is a feature from me :). New appointment should be greater than previous appointments. What do you think ?

-
