### ISSUE TITLE
Outlook Calendar export - authentication fails 

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#196]
I tested the Outlook calendar export - and was not able to really test. The authentication fails - or better said: it either delivers a white page instead of a Login Screen - or it delivers a Login screen, which does nothing after you entered your credentials and clock on the Login Button

After 1st klick on the outlook icon:
![image](https://cloud.githubusercontent.com/assets/11087531/20063913/243b80c0-a509-11e6-8c30-8fa42128c2c8.png)

Close Dialog and click again: 
![image](https://cloud.githubusercontent.com/assets/11087531/20063947/3d4eaf60-a509-11e6-95dd-299176c70186.png)

Doubleclick on Login-Button:
![image](https://cloud.githubusercontent.com/assets/11087531/20063985/5c4fb1ca-a509-11e6-831c-434a74b67502.png)

This is the URL: 
https://app.1clicktrips.com/api/outlook/authorize?code=OAQABAAAAAADRNYRQ3dhRSrm-4K-adpCJU7qRhynmnEmSEiOQ3cB1LIvvONRedJdcJ0zzF7eGJnujVMRS80i01GniAAAd3onCZvWVvfM1DT0X3IU5gHG0TuFmOzUmKCgPpN7THKnFaT7bKFAsvSL0H2JC9s8lSNBEt_BNCFteCVGjCSIIbM5aXyKv8p22UtnD_QC1vaaawKEhEcyTUjSN_IsScW4CkCyHpQ4SBQKRJMWWnhDs_vw6dXD7A8cjeTcIeGJSFcjJRAcBZydhDnoLMFB4FcQSmJnVVv9u5rCM_RZYZz_siD4bIiQlgYzdHfksMRVxwjNr-b5aoQRBMDTQY7ZfuV4IgdYLXqCmlxuD8n1PgJ7BlL_TjMaVzUrP1s5RAqq0IJtt09sN3mrdjSdSdgaTscEUsUgV37LC34psfp9rmTCmPH8-7Fo2MxRoWfRM99cUED7-xk4D4Du-woLDgzD9jK-JvkwnVcCE1xyOtJNlefdh04nb9UCJ156-0zHr64M7xSgzCxx0SvZBmCaRAq-Dz1OkI9EO0P8J-Y_XjGVGihDm4PbnTkbAj69UOAkUrpTF0roCGszs_cOtXQNI3SNuefyzIeaVsSJj38blUECfbPRGweVtIjwXPxSNo5cgBF7BhAtmARXDAxHsKB7Jq7nCAtF_zCA5lPC1L66yPOZ5JnttaWCYeexNeLKmuK_4GscwBOMV2bXm-HUBuqix7OTGJZeyvW_bYCXAdAIxg-6hZCgIipylzvWkDx4yEUKAf4zNRJIBUg8Be7K1l2-EPW4yQ3GBvEWEsOv5SaVoPdZlmqc-mwKewDnOhXg0n4lV82Ux134XMRlDnUbA0qPUv6nD5GL418bjIAA&state=abcd&session_state=16da1c98-2779-45df-aaf2-380aea4a1aa9

Thats it...I can´t get a step further

**Comment by davidtran** [comment]
I just test and it works.

**Comment by davidtran** [comment]
duplicated with #208
