### ISSUE TITLE
2016-11-19 Improvements-List for basic fixed to discuss

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#197]
This is a list of small things i have on my mind and want to discuss with @davidtran : 
Functional things
- Language selector shou.ld be on right side (where we´ll put the hamburger menue, too) 
- Logo quality is poor and needs improvement
- introduction screens needed like in Outlook Add-In
- add hamburger menue with Login | about us | help | settings 
- add software and deployment version in the hamburger menu in setings / info
- modify date display: European display is dd.mm.yyyy / English display is mm/dd/yyy
- add some useful features for enduser stuck in the process - like contact data / chat / feedback
- enhance waiting animation further by estimating needed time upfront - perhaps moving progress bar, enhance animation text and beautifx everything
- add sort options to the itinerary selection (default: 
**Fastest**: sort by total time then arrival time before meeting (less is better)  then # changes then price
**Most efficient**: sort by min. # of changes then by time and arrival time before meetng (less is better) then by price
**Best price**: sort by price then by total time then # changes

we have to ensure that users will later be able to select a default for their result sort in their user settings
- we should enhance the "progress bar" on top to show that the 1st step was search 2nd was select itinerary and 3rd is book & go - we don´t have just two steps
- 
get rid of login issues with Outllok calendar exporter
- improve look and feel of booking buttons

Non functional things
- ensure quality in dev- and deployment process
- ensure proper development documentation
- move everything from the frontend to the backend that should be handled better in the backend - ensure that the API keeps being updated
- ensure that FE does not modify persistence improvement measures by frontend implementations

**Comment by davidtran** [comment]
Hi @GrosR .
I have some questions:
- How to improve logo quality ? Is it blur on your browser ?
- We should have a contact page and a chat widget at the bottom of website ?
- About items in the side menu, we should create those pages first and add the link to side menu later...
- I will create a dropdown for sorting options. 
- I think the waiting animation works well already, so we should modify it later, after finish the important tasks.
- About the outlook login, I think it is the server issue, it doesn't forward the request to backend sometimes. I will discuss with Khoa to solve it.

btw, I think this list is long. so we should create the github issue for important tasks first

**Comment by GrosR** [comment]
Hi Nam,
Sure .. the list is just a summary to get an overview.... we shall create an item for each position.

As I move my apartment today, I am limited in time and web access..

Logo quality: don't know the reason, all browsers show it smeary ... let's ask Damian

Chat and Contact .. yes

Items in side Menü- fully agree

Test: ok, talk later

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by davidtran** [comment]
@GrosR the first step is the search page, right ? I think we can add a link like "Refine search"...

**Comment by davidtran** [comment]
Most of tasks in this issue has been fixed so I close it.
