### ISSUE TITLE
Sort dropdown for itinerary

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#199]
We have 3 options for this dropdown:
- Fastest: sort by total time then arrival time before meeting (less is better) then # changes then price

- Most efficient: sort by min. # of changes then by time and arrival time before meetng (less is better) then by price

- Best price: sort by price then by total time then # changes

**Comment by davidtran** [comment]
@GrosR you can test our dropdown on production website

**Comment by davidtran** [comment]
There are some text that need to be translated https://github.com/clowdfish/ttg-frontend/blob/version-21-08/app/i18n/de.json

**Comment by GrosR** [comment]
cool - works well
