### ISSUE TITLE
Sorting of appointments

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#20]
When adding a new appointment that starts before the appointment that you entered before, the order must be changed. The appointments must be always sorted chronologically.

**Comment by swapzone** [comment]
Not fixed yet.

![screen shot 2016-07-02 at 12 31 49](https://cloud.githubusercontent.com/assets/5637811/16539897/03a1e100-4051-11e6-9376-5ffdb0c24c09.png)

**Comment by davidtran** [comment]
I thought that I only need to do that in the result screen :)

**Comment by swapzone** [comment]
I did not explicitely think about it when writing that issue, but after testing it, I thought it to be better if the order is consistent in all screens.
