### ISSUE TITLE
Read git commit hash and deploy date and show it in setting page

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#201]

**Comment by davidtran** [comment]
@GrosR now when you go to website and open the browser console. You will see commit hash and commit date at the first line of console log

![screen shot 2016-11-22 at 5 37 45 ch](https://cloud.githubusercontent.com/assets/1154740/20520676/69f5c3b4-b0da-11e6-8e5b-cd19cccf01c0.png)

**Comment by davidtran** [comment]
Not sure how can I put them in the setting page.

**Comment by GrosR** [comment]
ok, i would have assumed that you can write the release info into a logfile or database and read it from there,... but I am fine with this approach
