### ISSUE TITLE
Book &Go Screen: Outlook-Exporter hangs on Authorization screen

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#208]
When I click on the Outlook Exporter Button, it opens the authorization screen ..this takes quite long and sometimes, the window is not pushed to the front, so you miss to realize that there is something to do. 

Once you register with correct credentials, the Login Screen asks you to authorizes 1ClickTrips to use your calendar. 

Once I confirm that, I get this screen: 
![image](https://cloud.githubusercontent.com/assets/11087531/20865453/a0fa271a-ba12-11e6-86dc-a4d0cfa53afa.png)

This is the URL where it hangs: 
https://app.1clicktrips.com/api/outlook/authorize?code=OAQABAAAAAADRNYRQ3dhRSrm-4K-adpCJ3mMQOgwVbfdx_BQHz6i6O2_x6ex9kghoFIfeo-YnjIa4SKrYt0mScgTtv5MVKz9J6BpuOxKChHlC3Rq5_nngin9bRKbTresnxFPureeQAPKUaqUpsgDKmzvb7c_kaESJjmN_1j0RnQwjhmNUhQmU8H7d9Upl-e9MR0A7pXYKP5q6ghyoxWo_2C2JQE-J4ifeckal0rlkxi55k7OEs3jGhy1bBriSdOjOeKSS1CN7VgsmjwUiNVb2B7Z0QYwZuTbPHPBj8d85xhDf7PAGffu8Q3vdTl-iiuDZiNxaOT1GVkL-dG0Fy5Vae6NH53NsPqT2KtZIrvpx0qHfrfvtz-GLiiHycjmHs4UgQXn9ZoMS27NhWiHnETVex1hkszSMNX943GNMM_5lgNIdaWiIJPwLfjFx8CdKNSCNF_Qos0--KXNayLHH45q02nwzk9Pq9lirMvr36t7_J3oNXrmNXn68YgivqMggiIMW9N7YGasLcxGCjXlPep75IDV949faPwaK4lq6d-nX3s35Jg1dZlFbJljfrlaHW5Yks-UEgSie4jG2HhQoBibSnJHFuO5uHOKdAinKo9Flt9CVjCJJBvgOs9nItQyGM2_-B3JWMx3bTiesLHmOpa1s5n8BTsGScNaFpeVFgn2--z9e7RpaX86TryYlocl4P2DyX90iDRWOTVO2bf4ZMM7sG63PEpk4DJJUOpw_3ED9Edn8_LxMRytDeVcU4-wUwd3E_1tZhED9JgtdpZNrfdz5fF2vDPxaHnBjACc6bDUad2pbjqBrUzYyJdh6XrGKiIybzM81ec3VLyyoDyPNZb_1J1uyw3nHjFj4nrjT_KUegvO4OaP0iyT3DSAA&state=abcd&session_state=163883d6-b286-40ad-a430-2c7d1830c4d2

I tried this with Chrome, Edge and IE

**Comment by quaywin** [comment]
Let me take a look

Get Outlook for iOS




On Mon, Dec 12, 2016 at 10:45 AM +0700, "Nam Tran" <notifications@github.com> wrote:












Assigned #208 to @quaywin.

**Comment by quaywin** [comment]
Hi Nam, I got this too
![aaa](https://cloud.githubusercontent.com/assets/7986870/21105045/6bd2c95c-c0bb-11e6-8c83-c6351dcabfeb.PNG)

**Comment by quaywin** [comment]
Due to the server is missing environment file right now, and it couldn't call to outlook app id and secret key. Then API couldn't return redirect URI.

So we should make a copy file `.env` on server.

Hi @vankhoa011 ,
Let you make a copy file `.env` from `.env.example` after build server of `ttg-api` repo

Thanks,
![env](https://cloud.githubusercontent.com/assets/7986870/21109398/7aad7f84-c0cb-11e6-9a48-bf35dde09701.png)

**Comment by vankhoa011** [comment]
@quaywin @GrosR : Please check again.

**Comment by server-clowdfish** [comment]
@quaywin : 

```
ubuntu@App1ClickTrips:/var/www/ttg-api$ cat .env
# BEGIN ANSIBLE MANAGED BLOCK
SITE_URL=https://app.1clicktrips.com
OUTLOOK_APP_ID=XXX
OUTLOOK_APP_SECRET=XXX
# END ANSIBLE MANAGED BLOCK

```
I added .env file in the root project.

**Comment by quaywin** [comment]
How can I reach project and watch log?

**Comment by quaywin** [comment]
It's working after we add path for environment file.

**Comment by GrosR** [comment]
Yeah+
