### ISSUE TITLE
Hotel booking - Version 1

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#213]
to integrate booking of hotels., we use a simple approach first. 

This item is not a real spec, but a rough description of hopw this evolution stage shall work. 

We use the booking.com Affiliate integration options and build a filtered overview list of hotels. 
Filtering shall be done - at this initial stage - by few criteria. We show hotels, that 
- are near the location of the meeting 
- near means either in near distance or shoprt travel time
- we always show hotels with a 3 star rating or more
- we show only hotels with best user satisfaction 
- in the resultset we create by these filters, we prioritize "the cheapest", "the best rated" and the "best value (price: to rating)

- we show the thre best optiosn first - and offer the option to browse further hotels

To filter the hotels, we will probably need to build a database from the data provided by booking.com

if a user clicks on details on a hotel, we show relevant details, like user ratings, pictures, comfort features. 

booking will be done by deep links at this stage.

I´ll try to go into more details - but need your support here - I am not aware what we can get from the available tools.

**Comment by davidtran** [comment]
There are few things from hotel dataset of **booking.com**:
- In hotel dataset they don't provide rating ( it is always 1 )
- Currency is not always USD, sometimes they use local currency. We have to convert it to USD.
- There is only one picture of hotel. So we can't make the details page... We have to redirect users to booking.com hotel page to get more information.
- Features (breakfast, smoking, kitchen) are not available

**Comment by GrosR** [comment]
Hi Nam,

Can we popup the booking.com<http://booking.com> hotel details page in an iFrame or popup, once a user wants to see details of a selected hotel ?

Perhaps we can get the hotel ratings from a webservice like from TripAdvisor, when we load hotels in a resultset ?

Currency conversion .. we Must probably convert according to users currency and language settings, so we need to maintain a conversion list


Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by davidtran** [comment]
Yes, we can display hotel details page of booking.com in an iFrame.

We can't get hotel rating from TripAdvisor. It would be inaccuracy because we have to scrape data and compare hotel name..

**Comment by davidtran** [comment]
There is an epic for this issue #217
