### ISSUE TITLE
Trigger a deployment whenever deploy on every push to a branch.

### ISSUE THREAD

**Issue by quaywin** [clowdfish/ttg-frontend#218]
@quaywin commented on [Thu Dec 08 2016](https://github.com/clowdfish/ttg-search/issues/100)

Hi Khoa,

As Jenkins CI, we want it provide some features such as:
- Server ttg-api will be run shell scripts `npm update` after we push code to `develop` branch of ttg-engine repo.
- After deploy successful, it will send a notification to the slack channel by Jenkins integration. The title message of notification is the commit content from ttg-engine.

**Comment by vankhoa011** [comment]
@quaywin : Okay , I will do that.

**Comment by vankhoa011** [comment]
@quaywin : ttg-search repo ?
