### ISSUE TITLE
booking page - hotel near generic bug 

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#223]
for some reason, our trip engine does noit set a location for a calculated overnight_ 

this leads to 

![image](https://cloud.githubusercontent.com/assets/11087531/21197026/37b67670-c23a-11e6-95c2-e05cba537b26.png)
hotel booking link without location.... and therefor to an empty hotel list ... which does not even show an error-message

**Comment by quaywin** [comment]
Hi Nam,
In case, which data do you need to show for hotel information?

**Comment by davidtran** [comment]
This error is already fixed on the front-end.
