### ISSUE TITLE
Configure CORS for API server

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#225]
Because we have removed proxy in webpack config in #224 so we have to setup CORS on ttg-api. 

@quaywin Please make our ttg-api accepts connections from http://localhost:8080

Example at here: https://github.com/BigstickCarpet/swagger-suite/blob/master/samples/CORS.yaml

**Comment by quaywin** [comment]
Hi @davidtran , I have added CORS to server middleware . You can check it again
