### ISSUE TITLE
Improve travel options screen

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#24]
In the travel options screen, it always says FLIGHT OPTIONS but it should be something like TRAVEL OPTIONS. Then underneath the map (before the hotel selection) we should show details of the selected trip. Something like:

Details to your flight / train / drive to Washington:
8:00 Departure at ...
10:00 Arrival at ...

Operated by Lufthansa.

![screen shot 2016-06-25 at 09 29 29](https://cloud.githubusercontent.com/assets/5637811/16355464/a1f9d5aa-3ab7-11e6-9f21-0a6157c4c9c2.png)

**Comment by davidtran** [comment]
ok

**Comment by davidtran** [comment]
![screen shot 2016-06-29 at 11 46 13 am](https://cloud.githubusercontent.com/assets/1154740/16440764/200abe34-3def-11e6-8047-fe6224d8a93b.png)

It would look like this. Tell me if you want to change something.

**Comment by swapzone** [comment]
Looks good to me! If you want to make sure, also ask Ruediger.

**Comment by swapzone** [comment]
Well done! WE probably need a icon for each row, but I will create a new ticket for this.
