### ISSUE TITLE
Think about deployment of test page

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#27]
We somehow have to show the app to Ruediger. Can you please figure out where and how we can deploy the app for him to test it?

**Comment by davidtran** [comment]
The easiest solution: we run our website on localhost and use https://localtunnel.me/ to let him access our website.

**Comment by swapzone** [comment]
Great solution!

**Comment by davidtran** [comment]
Cool, I will try it

**Comment by davidtran** [comment]
I added demo.js which we can run to start both frontend and swagger by localtunnel.

**Comment by davidtran** [comment]
Finish but localtunnel doesn't seem like reliable. It broke sometimes before really start: https://github.com/localtunnel/server/issues/14
