### ISSUE TITLE
Verify booking page

### ISSUE THREAD

**Issue by davidtran** [clowdfish/ttg-frontend#3]
Hi Sascha, could you verify it.

This is current bookings page.

![screen shot 2016-06-15 at 4 52 49 ch](https://cloud.githubusercontent.com/assets/1154740/16075581/b01d6476-3319-11e6-97a8-8a8901ded8d7.png)

Some segments doesn't have time because we don't arrivalTime and departureTime. I guess it's okay since those segments are not important.

**Comment by swapzone** [comment]
That is okay. I try to include all timing information for live data, but as long as the front end still looks good, when timing information is missing, I am happy.
