### ISSUE TITLE
Integrate template cache

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#31]
I could not manage to integrate the angular template cache together with web pack.
Please integrate it and give me an example how to use it. Therefor you should:
- create an example html tempate
- load this template with a webpack loader
- use it as require
- use it in html (without binding it to the controller) --> see uib typeahead widget as example (you can only add a path there, but doing it with Angular data binding did not work in my case...)

**Comment by swapzone** [comment]
Can you add a short description in here, what you did do?

**Comment by davidtran** [comment]
I put content into $cacheTemplate like this:
$cacheTemplate.put(url, content);
You can use any url as a key, when typeahead load the template url, it will take html content from the $cacheTemplate. No http request is needed.

**Comment by swapzone** [comment]
Can you give me an example in the code?

**Comment by davidtran** [comment]
ok,

at line 23 of departure-location.directive.ts you see this code:

constructor(private $q: angular.IQService,
              private addressSuggestion: AddressSuggestionService,
              private $templateCache: ng.ITemplateCacheService) {
    let typeaheadTemplate = require('./typeahead-template.html');
    this.$templateCache.put('typeaheadTemplate.html', typeaheadTemplate);
 }
The content of template is loaded using the require function. We use
$templateCache to put that template to the cache.
When angular look for the template, it will go to $templateCache first to
see any cache is available and provide the template for the directive.

After that in the template: departure-location.html. You see this at line
10:
typeahead-template-url="typeaheadTemplate.html"




2016-07-02 17:58 GMT+07:00 Sascha Gros <notifications@github.com>:

**Comment by swapzone** [comment]
Cool, thanks!
