### ISSUE TITLE
Use icons in travel options details

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#33]
Instead of the numbers in the list, we could use the icons for plane, car, ...

![screen shot 2016-07-02 at 12 37 21](https://cloud.githubusercontent.com/assets/5637811/16539920/ea3ffba6-4051-11e6-81a9-0b77e620f4e1.png)

**Comment by davidtran** [comment]
We need more icon images, currently we only have icon for flight, taxi, train

**Comment by swapzone** [comment]
Alright, will try to get them asap. We need icons for car, bus and walking, right? Anything else?

**Comment by davidtran** [comment]
I think "ship"

**Comment by swapzone** [comment]
Deprecated task.
