### ISSUE TITLE
Start Screen - Departure Location

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#37]
When I used the screen for the first time, I simply overlooked to fill out the departure location as the appointment form is dominating the screen.

I think it would be good to disable the appointment form until the "departure location" field is filled out.

Once it is filled out, the appointment form shall be activated and the cursor should be put it the appointment  name form.

**Comment by davidtran** [comment]
I think instead of disable the form, we can can hide form to prevent distraction from user. We show the form until user has selected departure location.
