### ISSUE TITLE
Start-Screen - Save/Delete-Buttons in  the Appointment form

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#39]
I checked the UX-workflow and agree to Nams suggestion to change the workflow a bit: 
- When leaving the appointment destination field, we should save the appointment automatically and set the cursor the "Search"-Button. 
- a saved appointment should be set in "edit-mode" when the user clicks on an item
- a saved appointment should have a "delete" option that can be clicked without further efforts to delete an appointment already entered
- If a user has the cursor focus on the "Search-Button" and uses the "Tab"-key, the focus should be set to the "Add New Appointment"-Button

**Comment by davidtran** [comment]
"a saved appointment should have a "delete" option that can be clicked without further efforts to delete an appointment already entered"

We already have delete button, do you mean that we should have delete button even when appointment is in "non-edit" mode ?

**Comment by GrosR** [comment]
I think we should autosave the appointments when a user leaves the appoinment tile with tabs or by clicking on the "Add next appointment"-Button. 
If the user leaves the appointment tile without entering an appointment location, we can ask if the appointment shall still be saved or deleted. 
Once an appointment is saved, we should provide the user with a "Delete"-Button. We don´t need the "Delete"-Button, before the appointment has been saved - we need it only when a user starts to edit an appointment after the initial saving.

**Comment by davidtran** [comment]
Already implement
