### ISSUE TITLE
Start Screen - Drop ICS File

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#41]
This feature is either not implemented yet or the .ics files are not recognized as .ics files. I uses .ics files from MS outlook and Google Calendar. 
If you drag an .ics File to the dropzone, the cursor changes it´s behavior, dropping does not execute an event.

**Comment by davidtran** [comment]
I have replace the ics parser by another library. Now we can parse multiple events in one ics file.

**Comment by davidtran** [comment]
- New todo item: show appointment even if the ics file is missing location data

**Comment by GrosR** [comment]
I tested different .ics files and the parser does not behave like expected. I attach the files I tested to let you try yourself.
[ics-files.zip](https://github.com/clowdfish/ttg-frontend/files/401847/ics-files.zip)

From my perspective, we should at least tell the user if we can´t handle an ics-file. If we know what is missing, we should tell the user that the ics-file is no valid appointment-ics due to missing information in field xxxx

**Comment by GrosR** [comment]
I just tested .ics files in the current release from 12.08.2016. 
I dropped a valid .ics file and the appointment card is created - but no new appointment card is created and it is not possible to edit the appointment card. 

![image](https://cloud.githubusercontent.com/assets/11087531/17642333/3bad562c-6141-11e6-848f-7f22d08301c8.png)

From that point on you can only click on the Logo to start over

**Comment by davidtran** [comment]
Done!
