### ISSUE TITLE
Start Screen - Appoinment Name and Appointment Location

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#42]
I entered several appointments and found out, that it would be better to enter the appointment location first and to prefill the Appointment name with the Appointment location name. 

As we typically enter company names and not addresses, it makes sense to name the appointment like the company you use and perhaps add some comments, if one likes. 

I assume that most users will just skip the appointment name and search directly .

I think it makes sense to try to change the position of appointment location and appointment name. Ideally we create two versions and run A/B Tests

**Comment by davidtran** [comment]
I will swap the position of appointment location & appointment name.
