### ISSUE TITLE
Change selected route border

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#46]
I chose an itinerary and the chosen flag appears at the calendar symbol and the itinerary collapses. So far the behavior is ok. 
If I click on the planned appointment in the left pane, the itinerary options are displayed in the middle pane, but there is no indication which one is the already chosen option. 

We should give the chosen option either an icon or a color coding to make it visible to the user which option is already selected in which ones would be alternative options to the one already chosen.

**Comment by davidtran** [comment]
How about changing the border color like this ? 
![screen shot 2016-07-08 at 3 55 57 ch](https://cloud.githubusercontent.com/assets/1154740/16682374/82ffe6cc-4524-11e6-8c04-ade119263725.png)

**Comment by GrosR** [comment]
I don´t think that we need the "Choose"-Button at all. If we highlight the item with the green border once a user has clicked on an item, it is clear that it is selected.
