### ISSUE TITLE
Travel Options Screen #5 - Map

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#53]
I realized that the map on top of the screen is used to display all map views from any item on the page. The basic idea makes sense, but from a UX perspective, I would not expect a map display at the top of the page when I click a map link or button at the bottom of a page.
I also realized that zoom factor of the map scales for each map link differently - I don´t understand on what information the scaling factor is chosen.

**Comment by davidtran** [comment]
So what should we when user click on map link ?
