### ISSUE TITLE
Start Screen - Show Results including Return Trip

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#59]
From my perspective, the Checkbox should be preselected with "Yes" by default. 

Additionally, It happens that users want to have a return trip, but to another location. We should therefore not only show the Return-Destination in the label, but should wrap it with a link to allow the user to enter another Return-Destination. 
![image](https://cloud.githubusercontent.com/assets/11087531/17055873/006e545e-5010-11e6-9932-f72f9cede9c1.png)

Ideally, we would open a tile that looks like the Departure Destination..
![image](https://cloud.githubusercontent.com/assets/11087531/17055893/28e7c992-5010-11e6-84a5-d7c5f30b7175.png)

..but is labelled with the name Return Destination.

**Comment by GrosR** [comment]
Just in case it should not be clear: The Return destination tile should be opened below the last appointment, in case someone clicks the location name in the label of the Return-Trip label
![image](https://cloud.githubusercontent.com/assets/11087531/17055968/91da6a86-5010-11e6-8d24-3c42d439c53c.png)

**Comment by davidtran** [comment]
Here is what we got when click on the return trip name
![screen shot 2016-07-26 at 4 56 38 ch](https://cloud.githubusercontent.com/assets/1154740/17133836/fd46b9de-5351-11e6-9817-9c74efd4c5b2.png)

@GrosR
