### ISSUE TITLE
Styling the calendar

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#6]
Style the location suggestion and calendar popup.

**Comment by swapzone** [comment]
Still have to style the calendar popup.

**Comment by GrosR** [comment]
see also #58

**Comment by davidtran** [comment]
Done!

**Comment by davidtran** [comment]
![screen shot 2016-09-19 at 3 45 29 ch](https://cloud.githubusercontent.com/assets/1154740/18626574/1bdfaa0a-7e80-11e6-8d9f-017c3495c2b5.png)
