### ISSUE TITLE
Start Screen - deleting an appoinment

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#60]
When an appointment is deleted, the labels in the other appointments must be updated with the correct number of left appointments. 
Sample: 
I added 3 appointments. Thhe appointments list looks like this: 
![image](https://cloud.githubusercontent.com/assets/11087531/17056015/eb69f454-5010-11e6-8c5d-85e27af0aa6a.png)

I deleted an appointment. The label still shows the same.

**Comment by davidtran** [comment]
I can't reproduce this bug

**Comment by GrosR** [comment]
I can`t either.... so it seems that this has either been "autofixed" or it has been a browser Cache-Issue. We can close this issue
