### ISSUE TITLE
Drag & Drop ICS-File 

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#61]
In case an .ics file seems to be invalid, we should display a message to the user, that this ics-file seems to be invalid. In case we know already what´s wrong, we can display the identified reason. 

We should add a link to the messagebox that allows the user to browse the .ics-file. If a user clicks on this link, we should expand the messagebox and allow the user to see the ics-file in read only mode in a kind of text-editor, that allows to mark and copy entries from the ics-File to ease manual data entry into our appointment form

**Comment by GrosR** [comment]
[Nintex Product Launch Webinar - PM.zip](https://github.com/clowdfish/ttg-frontend/files/378113/Nintex.Product.Launch.Webinar.-.PM.zip)

Here is a sample .ics File that can´t be imported. I assume it is because there is not location information and as there is a lot of time zone information stuff in it. 

We should be able to handle timezone issues in meetings, too. So, if  a meeting takes place in Pacific day time and the user is located in e.g. a UTC+1 Zone, we should be able to translate the appointment time to the correct time

**Comment by davidtran** [comment]
@GrosR 
Because we still show the appointment anyway, I think it's best if we show error message right in the appointment card.

For example: datetime error message should show under the datetime picker
