### ISSUE TITLE
Drop .ics - validation errors

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#64]
I dropped an .ics file that was correct in syntax  and form, so it was imported correctly. 

Once I hit the search button, the system told me that there was a validation error with the appointment. it took me a while to find out that the date from the .ics-File was before the current date. 

I assume that the **form validation should be applied at import time with ics-files, too**, to ensure that not only syntax, but also semantical validation is correct

**Comment by davidtran** [comment]
Done!. Appointment card will be filled by ics data and if there is any missing data, they will be shown when user click "add another appointment" or "search" button.
