### ISSUE TITLE
Return flight needs special design

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#65]
As the return flight is a special kind of thing for any traveler, we should design it differently from the other appointments. I assume we should have another Icon than the appointment icon and we could change the colors for the return flight, too. 

I´ll discuss that with Damian

**Comment by damianmartone** [comment]
This is also done in the itinerary.html file
As we added questions and return to the sidebar, and the return might be a plane or a train (depending on the last city you are in) theres now an option for return, that will have a similar right side as when selecting a flight

![screen shot 2016-07-29 at 11 39 22](https://cloud.githubusercontent.com/assets/8942032/17244250/35cbbb0c-5581-11e6-91fd-52a3a80757ab.png)

**Comment by GrosR** [comment]
perfect
