### ISSUE TITLE
itinerary selection - select route behavior

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#67]
When we select an appointment, we have the best option preselected: 
![image](https://cloud.githubusercontent.com/assets/11087531/17057611/63c68278-501b-11e6-8b49-0db0cf3af973.png)

I like the design that allows to just click the desired route and that the selected route has the green frame. 

To keep this style consistent, the rest of the behavior must be the same, which is not the case at the moment: 
- when we click the "tap to expand" link, the green frame must be moved to the alternative that is equal to the one that has been suggested at first: 
![image](https://cloud.githubusercontent.com/assets/11087531/17057692/ff7d981e-501b-11e6-99ef-dfc3c067ff93.png)

To select another option, a user should not have to click the "price"-Button, but shall click the other option and the green frame shall be moved to that option, as it is done on the other screens before. Additionally, the data from the chosen option shall be updated in the "Route"-Display, so that the Route ralways reflects the chosen option. 

We should ensure, that this behavior is coinsistent in the whole system. Once an item gets selected, it gets the same style. We should therefor have a CSS-style for the state selected and a style for unselected.

**Comment by davidtran** [comment]
Should we keep this behavior for the trip options page ?

Right now, when click on flight, it will go to hotel section. And when click on any hotel, it will go to next trip.

**Comment by GrosR** [comment]
Hi Nam,
the behavior should be intuitive and sensible :-) But I am not sure to understand your question referring the screens above. 
On these screens, you can´t select select hotels. You can select a "route" and you can select timing alternatives for the chosen route.
These use cases are possible: 
a) select a route an proceed
The best route is preselected and has the style for a selected route. This preselection must not only set the correct style but also the item selected status. 
- the user can accept the preselected route and just click the "Next"-Button and the next appointment will be loaded. 
- If a user clicks another route, the clicked route will be highlighted with the style for a selected route and the status of this route will change to selected route. The user can click the "Next"-Button and the next appointment will be loaded. 

b) select a timing alternative and proceed
Every route that has timing alternatives shows the label "show alternatives" in the right side.
- If a user clicks on "show alternatives", the timing alternatives for the chosen route are opened. The alternatives route must show the currently selected route as the 1st route in the list.
a) the user does not change anything and clicks on the "Next"-Button. The alternatives list will be closed and the next appointment will be loaded. 
b) the user clicks on one of the alternatives, The alternative shall be selected and the route in the route overview shall be updated, The alternatives list will be closed. The user can click the "Next"-Button and the next appointment will be loaded.
