### ISSUE TITLE
itinerary selection - Display of appointments in the left bar

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#68]
The current styling needs some refinement. Price information and the location information need some padding to the right: 
![image](https://cloud.githubusercontent.com/assets/11087531/17057865/585e6408-501d-11e6-9a16-4d4d117407ef.png)

I would also change the information order to make information more readable: 

1st Line: Date & Time, e.g. 25.07.2016; 9 AM-1:30 PM
2nd Line: Appointment Name with CRLF: Mittagessen Rüdiger Gros + Andreas Heim
3rd Line: Location Information: Obstgartenstrasse 22, 8302 Kloten, Switzerland 
4th Line: Price Information, e.g. 1245.56 €

We could even play around with 3 views: 
1: Compact List View: Displays only 1st and 2nd Line. Allows hover with Popup*
2: List View: Displays 1st - 4 th line
3: Calendar View: Displays a Mini Calendar in the left bar and shows markers where appointments are. Depending on the appointment dates, the calendar shows 1, 2 or 3 month in a row. 

*Popup: the popup could contain additional information, like 
- List view display + map display of appointment destination and route + weathermap + ???

**Comment by GrosR** [comment]
During my tests with the Hotel selection, I found out that we need even more info in the display on the left bar. It is important to see, which route we have choosen, so we must enhance the List View pattern:

1st Line: Date & Time, e.g. 25.07.2016; 9 AM-1:30 PM
2nd Line: Appointment Name with CRLF: Mittagessen Rüdiger Gros + Andreas Heim
3rd Line: Location Information: Obstgartenstrasse 22, 8302 Kloten, Switzerland 
4th line: Route Information
5th Line: Price Information, e.g. 1245.56 €

As addition to the optional calendar view I want to add the comment, that if someone clicks or hovers a calendar item. we should show the List View information on hover an the popup view information on click

**Comment by GrosR** [comment]
We further need to allow 
- editing of the appointment-data
- changing of origin for this appointment
- deleting an item from the selection
- adding a return trip

**Comment by damianmartone** [comment]
Closing in favour of https://github.com/clowdfish/ttg-frontend/issues/84
