### ISSUE TITLE
Itinerary selection - Activities Label

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#70]
The "Activities label" should only be shown in case there are any activities to be displayed. This depends in data delivered from the backend.

**Comment by damianmartone** [comment]
thats something that I think belongs more to @davidtran since displaying it or not its about the code, not the styling/ux

**Comment by GrosR** [comment]
I added you to the assignment as there is no 'to be informed' or 'cc' feature in Github and I want to discuss with you, if we should hide or only deactivate the labels to show the user only what's relevant or to better show a standard set of options with active/inactive styling

**Comment by davidtran** [comment]
Right now we don't have any activities data from backend, so I just simply remove that label.

**Comment by damianmartone** [comment]
exactly lets leave it for when something like this enters the platform's functionalities
