### ISSUE TITLE
"Add to Outlook", "Add to Google Calendar"

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#73]
On the left side of an apppointment, we have the link "Print this" and "E-Mail this". 

We should add two Links:
"Add to Outlook"
"Add to Google Calendar"

**Comment by davidtran** [comment]
In order to do this, we need the backend to support generating ICS file

**Comment by GrosR** [comment]
ok, I^ll tell Sascha, even so I think we have that already .. but I am not sure. I? I´ll add a Github Item for this

**Comment by GrosR** [comment]
The Add to Google Links should allow the creation of all calendar cards in a single action, so we should not add these links to the individual cards, but to the top where the icons for print and e-mail are already

![image](https://cloud.githubusercontent.com/assets/11087531/18230863/7f796076-72a8-11e6-8b07-362dbff29250.png)

**Comment by swapzone** [comment]
@davidtran you already implemented the ics creation process in the ttg-api. Not sure if it is still in there, but it was in some version. Maybe it's also in the old 1ClickTrips repo.

**Comment by davidtran** [comment]
@GrosR so we remove "export to google" and export to outlook on the right side of each appointment ?

**Comment by GrosR** [comment]
I think this makes sense - unless we believe that users want to have the option to add each meeting individually. 
I doubt that this is useful - so I´d remove the links from the left side and add them on top in the hamburger-Menu

**Comment by davidtran** [comment]
ok, I will remove them from sidebar and move to the top. Since this issue is duplicated with #191 I am closing this issue.
