### ISSUE TITLE
book and go - E-Mail-Links

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#74]
The E-Mail links are not yet implemented. It should work like this:

If you click on the e-mail icon, a dialog should ask for sender and recipient e-mail address and we should log this in our systems. 
Further should the user be able to choose between itineraries with map or without map-info. 

If a user clicked on the E-Mail Icon on top of the page, all appointment pages should be rendered in a single PDF, 
If a user clicked on the E-Mail Icon  in an appointment page, only this appointment shall be rendered in a PDF.

**Comment by GrosR** [comment]
See issue #18

**Comment by davidtran** [comment]
I have researched and there is no way to add an attachment when open email editor. We can only prepare email subject and body.

So here is my propose:
We create a dialog by ourselves which user can input email, message.
We generate the image of booking screen on backend and attach to email.
We send it from our server...

But I think these steps will take us a lot of time so we should print the pdf and let user send email by himself.

**Comment by GrosR** [comment]
from my perspective, we can cancel send E-Mail .. we should replace this later by social share buttons
