### ISSUE TITLE
Add support for ics-creation to the backend features

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#76]
to help users add their trips as appointments to their calendar, we should add support to create ics-files for 
- Outlook
- Google Calendar

to the backend, so that we are able to let users create ics-files in the results screen
![image](https://cloud.githubusercontent.com/assets/11087531/17108501/24d04cc2-5294-11e6-9242-d38ad151fd72.png)

**Comment by swapzone** [comment]
Nam already did that in an old version. Must be ported and integrated in the current version of the ttg-api.

**Comment by davidtran** [comment]
This issue is done. I have to close it.
