### ISSUE TITLE
Start Screen - Location selector appears to have a Google API implementation bug

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#78]
I tried to enter EFEXCON AG into the appointment location and it displays EFEXCON AG, Leonberg, Germany (which has been closed 5 years ago) and EFEXCON AG, Switzerland does not exist. 

If I enter the valid address manually
![image](https://cloud.githubusercontent.com/assets/11087531/17130995/9375625c-531b-11e6-932f-db763a141134.png)

it displays this message: 
![image](https://cloud.githubusercontent.com/assets/11087531/17130950/623fa4d6-531b-11e6-89e6-4440237ec15f.png)

If I type the street address, it finds the valid adress: 
![image](https://cloud.githubusercontent.com/assets/11087531/17131040/be7ba146-531b-11e6-8982-8b0363113c3d.png)

...and I can add EFEXCON AG at the front, manually:
![image](https://cloud.githubusercontent.com/assets/11087531/17131065/e4001a1e-531b-11e6-883a-ca5c5689c296.png)

It seems, that the validation algorithm is not too clever at the moment...it should work reverse:
- check if country exists
- check if zip code and city exists
- check if street exists
=> Address exists
- check if company or location name exists
=> if yes: full qualified address
=>if no: address qualified, but company or location not found....still a valid addresse

**Comment by davidtran** [comment]
Currently, we depends on Google map API to resolve longitude & latitude. after that we send this information to our API. So if google map api can't resolve this address, we must mark this address as invalid. 
@GrosR

**Comment by GrosR** [comment]
I understand how it works. I do not understand, why the lookup does not find EFEXCON AG, Löberenstrasse 47, 6300 Zug, Switzerland.

This address is registered in Google places, in Google Plus and in Google Maps.

Still, our lookup does not find it..... That's why i think that there might ne a bug in the Implementation.

Could you check that ?



Rüdiger Gros
+41 44 586 5018
www.efexcon.com<http://www.efexcon.com>
EFEXCON AG.
Digitale Transformation durch Cloud, Business Software und Software Engineering.
Ihr Partner für SharePoint, Office 365, Azure, Dynamics CRM




On Wed, Jul 27, 2016 at 10:24 AM +0200, "Nam Tran" <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, we depends on Google map API to resolve longitude & latitude. after that we send this information to our API. So if google map api can't resolve this address, we must mark this address as invalid.
@GrosR<https://github.com/GrosR>

-

**Comment by davidtran** [comment]
I think you copy and paste the address, in this case the lookup doesn't work. I will fix it.

**Comment by GrosR** [comment]
Hi Nam, I didn´t copy the address, I type it in manually. Just try yourself. Enter EFEXCON AG in our lookup list and you will get EFEXCON AG, Leonberg, Germany. 
Go to Google maps and try the same: You will get 2 entries: 
![image](https://cloud.githubusercontent.com/assets/11087531/17240470/031d14b8-556c-11e6-929f-6bbe3b0e73f2.png)

But in our Lookup, we only see the 1st entry, which is wrong.

**Comment by GrosR** [comment]
I asked Google to remove the Dataentry für EFEXCON AG, Leonberg completely...they already confirmed that and mentioned that it might take up to 24 hours to reflect the change

**Comment by GrosR** [comment]
I still think that we have a bug in our implementation of the Google API. Please check the above scenario yourselves and check the results from the API when queriing EFEXCON AG

**Comment by GrosR** [comment]
I checked it once again and the delivered data is ALMOST correct, but we have to filter locations, that are no longer active, out.
