### ISSUE TITLE
Start Screen - complete behavior overview

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#81]
This issue is a summary to give an overview of the desired behavior of the Start page:

In the 1 step, we want the user to enter his departure location: 
![image](https://cloud.githubusercontent.com/assets/11087531/17137365/1cc23462-533b-11e6-8e70-35e22fcf0bf6.png)

To ease the navigation, we should replace the label "Type a location" by "enter your departure location". See issue #57. 

Once the departure is chosen, an appointment card is opened automatically. The card is meant to either enter data manually or to drop an .ics file:
![image](https://cloud.githubusercontent.com/assets/11087531/17137526/e01c4f1a-533b-11e6-8af2-fe5193a55da4.png)

In contrast to what we have now, I would like to remove the "Delete"-Button in the lower right corner and replace it by a trashcan icon in the upper right corner of the card. 

--------- **Appointment Card Section**
_Manual data entry:_ 
When data is entered manually, we have to validate data. Errors should be displayed directly below the data entry field(s) where the error happend. Error messages shall display user friendly action messages, like: "please verify your appointment location, the city can´t be identified". 

With issue #80 we request "autosave and autocreate" for appointment cards , **but** there is an issue we have to discuss and at least A/B-test: 
- if you enter data manually **and do not change** the date or time pickers (which might be ok!), the card is closed on leaving the appointment title field, 
- this might lead to irritation as one might still want to edit the date or time pickers and it is uncomfortable to have to click on edit to get back to the entry again. 
=> I see three possible approaches: 

1. when leaving an appointment card where data or time pickers haven´t been edited, we could keep the appointment card open with some delay and close it, if the user starts editing in the autocreated appointment
2. we set an appointment into edit mode if a user clicks on the closed appointmen card, even if the user does not click on the "edit" label
3. we don´t autosave the appointment cards and require the user to click on a "save"-Button. Once the save-button is clicked, we autocreate a new card. 

-------
_Data entry by ics-file_
Data entry by .ics file is described with the issues #41, #61 - #64 

A data entry via .ics has to be handled and validated like any manual data entry. However, we have to manage .ics files which might be corrupt, incomplete or that do not completely fulfil our requirements (like e.g. Online Invitations that do not contain location information).

In any case where we the .ics-Fiel does not cover our needs, we should fill out any field that we can. And all fields that we can´t fill should show a clear error-message, like: ics-file did not contain a location information. Please add one manually. 

------- **Remove this from screen:**
- we should remove the "drop zone" fpr .ics below the appointment cards, as the appointments themselves are drop zones
- we should remove the "add next appointment button" as we autocreate appointments as described in the **Appointment Card Section**
![image](https://cloud.githubusercontent.com/assets/11087531/17138459/afce8d32-5340-11e6-8297-e84806f49939.png)

------ Set Default for "Include Return Trip" to true
As travelers will typically return to their starting destination, we should set the default for the return trip to true

----Calendar Selector
The Calendar selector is not very convincing, yet. I don´t like the style of this thing and it should look like the rest of the screens. At the moment it looks like sth. that we plugged in from somewhere else.....

These issues have to be applied to fix the calendar to our needs: 
- #58. I´d prefer the styling of the google flight calendar
- #6 
- Calendar needs to start on Mondays, not on Sundays.

**Comment by davidtran** [comment]
@GrosR  Most of issues in this tasks are fixed, except for the calendar styling

**Comment by GrosR** [comment]
@davidtran Damian is going to make some slight changes to the screen, he will update that shortly...I´ll test your fixes and document the results

**Comment by davidtran** [comment]
ok, I will deploy website soon.

**Comment by GrosR** [comment]
ok :-)


Mit freundlichem Gruss

Rüdiger Gros
CEO EFEXCON AG
CH: +41 44 586 5018
DE: +49 711 518 66 990
Chat with me on Skype |Connect on Linkedin<https://ch.linkedin.com/in/ruedigergros> |Connect on XING<https://www.xing.com/profile/Ruediger_Gros> | Follow me on Twitter<https://twitter.com/grosonair>|

EFEXCON AG<http://www.efexcon.com/>, Löberenstrasse 47, 6300 Zug, Schweiz |HRA CH-170.3.028.944-5 |MwSt CHE-112.673.353 MWST | DUNS 483221813
Inbound Marketing. CRM. Office Produktivität. Portale. Custom Solutions. Ihre Software-Experten für SharePoint|Office365|Cloud und Mobil seit 2005.
Automotive & Suppliers | Industry & Production | Energy | LifeScience | HighTec | TelCo |Health & Medical |Logistics | Non Profit
Follow us on Twitter<https://twitter.com/efexcon>  | Follow us on Linkedin<https://www.linkedin.com/company/efexcon-ag>





________________________________
Von: Nam Tran <notifications@github.com>
Gesendet: Freitag, 29. Juli 2016 09:44:50
An: clowdfish/ttg-frontend
Cc: Rüdiger Gros; Mention
Betreff: Re: [clowdfish/ttg-frontend] Start Screen - complete behavior overview (#81)


ok, I will deploy website soon.

-

**Comment by damianmartone** [comment]
HI, unfortunately I wasnt able to run the frontend properly to make the changes there, so I kept working on the templates repo. Might be fine for now since we are making some important changes in other screens.

For this one here's the changes we discussed with Rudi

![screen shot 2016-07-29 at 11 09 50](https://cloud.githubusercontent.com/assets/8942032/17243415/02084550-557d-11e6-8888-2b8d46d638f9.png)

Changes follows:

- Switching appointment location and appointment name (also icons)
- Removing Search button, Drop ICS, and return trip checkbox
- Move the delete button to the opposite side of the CTA so the focus is on the save actions
- The logic will be: Add departure location, select it, new card appears, complete card, save card and add new one, new card appears, complete card, save card and add one, new card appears, complete card, save and start search. This way the two buttons are on each card and the user can add a new appointment or start the search by each card. The card should not "close" until the user has saved it.
- The return trip will be by DEFAULT (this is because of a change in the logic of the itineraries, see https://github.com/clowdfish/ttg-frontend/issues/85 ) therefore, we'll ask the customer if he wants a return trip or not in that next screen, simplifying this one.
- ICS drop will work, when the user drops an ICS file in the header of the card

Changes are made in the index.html in the repo, let me know if you have any questions

**Comment by GrosR** [comment]
Hi Damian, 
I do not understand the flow for the departure location. Could you explain your idea in more detail or with an example? 
Currently my understanding is: 
Variant 1: 
- You enter your departure location. This one is also your default as return destination. 
- You enter your 1st appointment. This one will start at the departure location. 
- you enter your 2nd appointment. This one will start at the appointment location of the previous appointment by default, if the appointment dates are within 24 hours, else the default departure location will be the one initially entered. This step is repeated for all ongoing appointments. 

In case a user wants to change the departure location set by default, he should be able to override the default within the appointment card. 

Variant 2: 
- You enter your departure location. This one is also your default as return destination. 
- You enter your 1st appointment. This one will start at the departure location. 

When the 2nd appointment is created, two cards are created: 
- a departing from, set by default according to the rules described in Variant 1
- an appointment card. The focus is set to the appointment card. 

Is your design meant to be Variant 2? Or even another one?`

**Comment by damianmartone** [comment]
`In case a user wants to change the departure location set by default, he should be able to override the default within the appointment card.`

my approach was by default to connect all appointments origin/departure, and allow the user in the itinerary section to change the departure location of each appointment if he desires to, being this an edge case. But if you'd prefer we can have a link that says "Departing from (previous card's location) click to change" in each card and then allow the user to change it in there before the itinerary happens

**Comment by GrosR** [comment]
I think that the link is a better way. In the worst case, a user would have to change every appointment in the itinerary section... at the current page the user will probably have his trip between the appointments in mind, 

On the other hand, a change in the starting location would help us on the itinerary page to ask further questions, like if the latest appointment destination and the starting destination are different and the date/times are close together, we could later ask if he needs support to get from A to B. 
But for now I personally find it easier if we have the departing from link in the card somewhere

**Comment by damianmartone** [comment]
yes, if not it gets too complex, should be 1clicktrips so the more automatic the better, then the user can choose to make it more complex but id leave the main flow as seamless as possible, with the possibility to configure, and not add any more screens in the middle

**Comment by GrosR** [comment]
yes, I fully agree. The link will give the user guidance about what he decides and doesn´t require any action by default.

**Comment by damianmartone** [comment]
@GrosR @davidtran  I've added a small text to the card that allows to change default (previous appointment) location for departure. Basically the user has the card he is editing like this

<img width="1124" alt="screen shot 2016-07-30 at 12 14 28" src="https://cloud.githubusercontent.com/assets/8942032/17269684/8d76299a-564f-11e6-8b31-f0638672ad28.png">

And can click on the link that says Departing from... CHANGE, and will have a new field added, pre-filled with the city from the last appointment, but with the possibility to change it to a new one.

<img width="1145" alt="screen shot 2016-07-30 at 12 15 56" src="https://cloud.githubusercontent.com/assets/8942032/17269683/8d748478-564f-11e6-859b-839b8a9be37a.png">

**Comment by GrosR** [comment]
cool. Now i think that the User workflow should be complete and the user experience is still simple and intuitive

**Comment by davidtran** [comment]
So user can change departure from any appointment card ?

**Comment by GrosR** [comment]
Exactly. This is necessary as the user can enter multiple appointments for different days and can start wherever he is at that time ..and even if a user has entered 3 appointments at the same day, we cannot know if the user starts directly from one appointment to another or takes a train in between to eat in his fVorite restaurant and start from there

**Comment by damianmartone** [comment]
yes, later on (in the itinerary selection) the user will be able to click CHANGE on each appointment to get an edit screen for that one, which will be very similar to this card he completed, so he can change the departure there as well.

**Comment by davidtran** [comment]
I am running in this situation, when I am editing appointment#2 and I comeback to appointment#1. The buttons make no sense. I think the button of appointment#1 should be "Save" only. We only show Start search and Add new button in the last Appointment card
![screen shot 2016-08-02 at 4 12 20 ch](https://cloud.githubusercontent.com/assets/1154740/17323380/330302e2-58cc-11e6-9b6a-d9fb1b970516.png)

**Comment by damianmartone** [comment]
@davidtran only 1 card can be open at the time, and that one should have the CTA. Lets say I had 5 appointments and made the mistake in no 3. I should be able to go to that one, correct it and start the search, or have the possibility to add a new (6th) appointment.

**Comment by davidtran** [comment]
What if user have not finished edit the 5th ? but he clicked on edit button of the 3rd ?

**Comment by damianmartone** [comment]
unless the card is fully edited we can't allow jumping back to a previous one, we can do auto-save if its full but if not, we need to alert "you first need to complete or remove this appointment"

**Comment by davidtran** [comment]
ok
