### ISSUE TITLE
Allow the user to change existing appointments after search started

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#82]
Once you hit the search button, you get to the **select itinerary** screen: 
![image](https://cloud.githubusercontent.com/assets/11087531/17138950/be7b1420-5342-11e6-9938-98f68ca64b10.png)

Now there is no way back to the search screen. 

We should either have a cool way to get back to the search screen to modify appointments there .. or we should allow to edit and delete appointments in this screen.

**Comment by GrosR** [comment]
We should also discuss if we allow to add the return flight from here, if a user has unchecked it on the first page. 

We could just add  the same link from the frontpage in the left pane to allow to check or uncheck return

**Comment by davidtran** [comment]
Actually, we can click on logo to back to search screen.

**Comment by davidtran** [comment]
@damianmartone  Once you have the mockup, please assign it back to me.

**Comment by damianmartone** [comment]
AS mentioned here https://github.com/clowdfish/ttg-frontend/issues/84 the user will be able to make changes in each appointment once that appointment is active
 
![screen shot 2016-07-29 at 11 22 45](https://cloud.githubusercontent.com/assets/8942032/17244024/fb34f07c-557f-11e6-90d7-b7e53109feef.png)

pressing "change" will open a lightbox screen on top of the itinerary, with an edit mode for the current appointment allowing to

- Change departure location
- Change name
- Change appointment location
- Change appointment times
- Preference: "Stay a night in a hotel" "Flight right away" "If there is time fly back to origin destination and return for the next appointment" etc

Design is in progress

**Comment by davidtran** [comment]
When do we show the preference options ?

**Comment by damianmartone** [comment]
when the user clicks on change, he should get a lightbox with the appointment card as in the main page, and an option group that has the preferences as a list

**Comment by damianmartone** [comment]
<img width="1440" alt="screen shot 2016-08-09 at 11 01 54" src="https://cloud.githubusercontent.com/assets/8942032/17510808/b682a862-5e20-11e6-8dfa-2275ab5a917c.png">

**Comment by davidtran** [comment]
@damianmartone  could you explain the effect of these radio buttons ?

**Comment by GrosR** [comment]
Hi Nam, 
if a user clicks on "Prefer to fly back to my origin point", please
- add a return flight starting from the location of the current meeting
- prefill the starting point of the next appointment 
- recalculate the trips

if the user clicks "prefer to stay in a hotel", take this as a "add a hotel option to the current appointment", so that the user will be guided through the hotel selection process after he has saved the changes. 

If the user selects "don´t book and flights or hotels", just save the appointment and go to the next appointment in the list.

**Comment by damianmartone** [comment]
yes exactly :)

**Comment by davidtran** [comment]
we might not need "stay in a hotel options" because we can select hotel for any trip.

**Comment by damianmartone** [comment]
well its just a preference, not a decision, so if the next appointment is the same day, there will obviously be no hotel, its more like.. if there is the option between days what do you wanna do?
