### ISSUE TITLE
Refine itinerary - align CSS for "selected" to the rest of the app

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#83]
In the flight options, we have the same issue like on all other pages: The style for "item selected" must be the same for all items on all pages. 

Please define ONE CSS-Style class for "Item selected" so that we have a consistent look in the whole system by changing just this style class. 

See the flight options: 
![image](https://cloud.githubusercontent.com/assets/11087531/17139726/eded8708-5345-11e6-82cf-a892ec3f3757.png)

Select the 1st item by default and highlight it with a green frame, like on all other pages. Remove the buttons.

**Comment by damianmartone** [comment]
Partially done in itinerary, trip options still in progress but will use the same styles
![screen shot 2016-07-29 at 11 26 20](https://cloud.githubusercontent.com/assets/8942032/17243966/b5143cec-557f-11e6-92a7-5c07a33305c2.png)

**Comment by GrosR** [comment]
What do think about enhancing the behavior to:
- Click once: select item
- Doubleclick: Select Item and click the "next"-button in a single action?

**Comment by damianmartone** [comment]
sounds good, its mostly an implementation thing for @davidtran we have to make sure it works on mobile also (tap)

**Comment by GrosR** [comment]
yes, I know it´s a job to do for Nam, I just wanted to verify that the user interaction fits your agreement. On the smartphone, I think that a doubleklick kan be simulated as 3D press on an iPhone or a long tap on Android and Windows Phone. 
In the end, I assume that we will need a mobile app with different features than the current ones as I assume that the real mobile usage requires different patterns.

**Comment by GrosR** [comment]
The styling of the upgrade options is still different from the styling of other options. The route option e.g. has rounded corners and 3 lines height, in between the options there is a space. 
We should use this style for all selectable options. 
For flight upgrade options, the styling should look like the route options (rounded corners, green frame, space between options. 

Additionally, the "No Upgrade2 option should be preselected.

**Comment by davidtran** [comment]
![screen shot 2016-08-15 at 1 05 25 ch](https://cloud.githubusercontent.com/assets/1154740/17656872/f56887d2-62e8-11e6-820d-06a09d9e4312.png)

@GrosR How do you think ?

**Comment by GrosR** [comment]
if you style the preselected item with the green border instead of full green, the rest of the design is fine : 
![image](https://cloud.githubusercontent.com/assets/11087531/17659517/5ba69a04-62d3-11e6-9140-64c07b353805.png)

**Comment by damianmartone** [comment]
exactly just green border, not full green
