### ISSUE TITLE
Start Screen - Edit behavior when a new appointment card is open

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#89]
I added an appointment and clicked "Save and add new appointment"
![image](https://cloud.githubusercontent.com/assets/11087531/17395805/8d9afe16-5a30-11e6-9339-9b0e1077d52a.png)

I haven`t entered anything in the new appointment card but wanted to edit an existing appointment card, as I saw that I made a mistake. 

As I haven´t edited anything in the new appointment card, I expected to be able to just click the saved appointment card for edit and then return to my unedited new one. This is what happens: 

![image](https://cloud.githubusercontent.com/assets/11087531/17395930/20907764-5a31-11e6-899c-96b81eb19af6.png)

If a new appointment card hasn´t been edited yet. we should allow to just leave the card and edit an existing one

**Comment by davidtran** [comment]
@GrosR @damianmartone I made it based on the discussion with Damian

**Comment by GrosR** [comment]
the current behavior makes sense, if the user has entered anything in the new appointment card. If the appointment card hasn´t got any changes and is exactly like a freshly created, it is better to allow the editing of existing cards without this question.

**Comment by damianmartone** [comment]
I agree with @GrosR if nothing has been inputed on the card, switching to a new one should just delete it. If even one single field was changed, we need the alert.

**Comment by GrosR** [comment]
right, that´s what makes sense

**Comment by davidtran** [comment]
make sense with me :)

if user didn't do any changes, we just simply remove the card. he can still able to add new card any via the "Save and add new appointment" button.

**Comment by GrosR** [comment]
exactly
