### ISSUE TITLE
Change behavior for itinerary selection

### ISSUE THREAD

**Issue by swapzone** [clowdfish/ttg-frontend#9]
When clicking on 'Choose' the screen should not go to itinerary details page, but hide all other options and just show the user, which itinerary he selected. Then the user must click 'Proceed' at the bottom of the page. Or he selects the return to departure city, then a new segment appears in the appointment section and the user must select the itinerary for his trip back home. Then again he has to click to proceed before coming to the next screen.

![screen shot 2016-06-18 at 10 29 06](https://cloud.githubusercontent.com/assets/5637811/16169898/9b1d7ff2-353f-11e6-95f4-48e1e5a9542e.png)

**Comment by davidtran** [comment]
What does proceed button do? Go to travel-options page or open the next appointment panel ? @swapzone

**Comment by davidtran** [comment]
I think this issue is duplicated with #11

**Comment by swapzone** [comment]
Okay, then we can close it.
