### ISSUE TITLE
Select itinerary Screen - Layout

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#92]
The layout and styling if the left pane seems not to be implemented yet: 
![image](https://cloud.githubusercontent.com/assets/11087531/17396383/78e3718a-5a33-11e6-8f65-e1c63b7db29d.png)
The "Change"-Link is overlapped by the right border, the Address of the appointment is missing, fonts seem to be missing, 

This is how it should look according to Damians Design: 
![image](https://cloud.githubusercontent.com/assets/11087531/17396485/ee8e6016-5a33-11e6-8f6c-cf3f4a32747e.png)

The design of the border of the screen whole screen seems to be not like designed, too: 
In the Design-Drawing, the grey area is limited to be a zone around the left and center pane, so the grey zone should be boxed and not float with screen width.

**Comment by davidtran** [comment]
It should be similar now, please review

![screen shot 2016-08-08 at 10 31 25 am](https://cloud.githubusercontent.com/assets/1154740/17468561/481d2b68-5d53-11e6-9140-6faef71257dd.png)

**Comment by GrosR** [comment]
the styling works now, still, the color styling of the start date does not work in the active cards. The start date is styled with white letters on white background.
