### ISSUE TITLE
Select itinerary - Styling Bug

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#93]
There seems to be a bug in the CSS around the Starting-Date of an appointment, look at these screens:
#1 I selected the route in an appointment and clicked next. Then I clicked into the 1st appointment, where i have selected a route already another time, so that we have two appointments that are clickable in the left pane now: 
![image](https://cloud.githubusercontent.com/assets/11087531/17396777/34848ebe-5a35-11e6-81b6-867e0a20ac7c.png)

Then I clicked on the 2nd item again and the Starting date "disappears", as the color seems to not change from white to black: 
#2 
![image](https://cloud.githubusercontent.com/assets/11087531/17396837/7507de50-5a35-11e6-8fa8-40c4dbc67ba6.png)

**Comment by davidtran** [comment]
I still can't reproduce this issue. It would be great if you could tell me the steps to reproduce it.

**Comment by GrosR** [comment]
The styling for the Startdate of appointments seems to have an error in the structure or the applied class: 
![image](https://cloud.githubusercontent.com/assets/11087531/17473142/25b98bce-5d4f-11e6-9946-e736323f6d46.png)

The Startdates always have the styling of the background, so you can´t see them
