### ISSUE TITLE
Select itinerary - Change appointment styling

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#95]
It seems to me that the styling of the Change appointment card has not been applied yet: 

![image](https://cloud.githubusercontent.com/assets/11087531/17397001/5ee51204-5a36-11e6-86b1-d1f42e1426b5.png)

The time lookups hide the time, the bullet options break the line and the buttons are missing the usual color coding

**Comment by davidtran** [comment]
Hi @damianmartone could you update the html on 1clicktrips-templates ?

**Comment by davidtran** [comment]
Just fix this issue.

**Comment by GrosR** [comment]
cool

**Comment by damianmartone** [comment]
looked good on the template
but if its fixed should we close @GrosR ?
<img width="1440" alt="screen shot 2016-08-09 at 11 01 54" src="https://cloud.githubusercontent.com/assets/8942032/17510909/2d05da90-5e21-11e6-938b-a5c8e9c8081c.png">

**Comment by GrosR** [comment]
yes, close it
