### ISSUE TITLE
Refine itinerary - header styling does not follow the workflow

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#97]
Once I finished my appointment and route selection and confirm everything, the system leads me to the "Refine itinerary" section. But the header styling still shows "Select itinerary". 

![image](https://cloud.githubusercontent.com/assets/11087531/17397279/94913fbc-5a37-11e6-83a3-4f3e46651227.png)

As "Select itinerary" is marked with a "hook" as finished, I think that it is just the issue the the color is not moved to the active section and the done section is highlighted green. The finished section should rather be dark gray with a green hook. 

Overall, i think the progess bar on top could be made sexier ... @damianmartone any idea?

**Comment by damianmartone** [comment]
we should have removed already the text and 'skip this step' from the top, and that way we'd see the progress on top. as we have 3 elements and they are marked done (1st) and active (second). When this top text and button are not there anymore, it will be visibly more clear on the link as a progress, but we can also think of a real progress bar if necessary, I just dont want to get more content into the panels

**Comment by GrosR** [comment]
I agree, I just want the navigation to be clear

**Comment by damianmartone** [comment]
@davidtran if we could remove the text/skip step on the top of each part and then see if thats enough
