### ISSUE TITLE
Refinement Section - Change&Remove behavior for options

### ISSUE THREAD

**Issue by GrosR** [clowdfish/ttg-frontend#99]
Currently, if you have selected and confirmed  a refinement option, you can click on the option in the left pane and select another item in the center pane. 

There is no option at all to remove an item once you selected one. 

The workflow should be the same as in the "Select itinerary" section: 
- Any item saved on the left side need a "Change" link. It should not be possible to change an item by simply clicking on an item in the left pane, the user must explicitly select the "Change"-Link to avoid unintended changes. 

@damianmartone We can either allow a user to "deselect" an item by clicking a selected item or we need some kind of "clear this selection" or "delete the option" -button 

The user will expect to either be able to "undo" a selection and to replace it by another selection or to skip this option. 

What is your idea on that?

**Comment by GrosR** [comment]
I just looked like we did in other case: 
- with flight upgrades, we have an option "No Upgrade"
- in the questions section, we can chose "Do nothing"
It would probably be the best thing to add a "fake Hotel" that is called "I don´t need a hotel"

**Comment by davidtran** [comment]
I've just looked at the hotel options and you are right, we need a options to remove selected hotel.
Where should we place the "I don't need a hotel" button ? Or we could click on the hotel again to unselect that hotel. What do you think ?

**Comment by GrosR** [comment]
Hi @davidtran , i am waiting for response from @damianmartone on that issue, I assume Damian will reply soon......

**Comment by damianmartone** [comment]
Well I always assumed the hotel was a bit mandatory since we are acting as a travel agency not a flight booking company, but of course the user should be able to refuse getting a hotel. This may cause hassle for him, but I would say the best path is

-Show the hotel nights in the itinerary selection, if he decides to change the appointment and select the no hotel option, then we can show itineraries without, otherwise he sees the itinerary with hotels
-Allow in hotel selection a card that says "do not book me a hotel for this night"

**Comment by GrosR** [comment]
fine for me

**Comment by davidtran** [comment]
So which changes I should implement in this task ?

**Comment by GrosR** [comment]
Hi Nam, 
please implement the described behavior last mentioned by Damian: 
-Show the hotel nights in the itinerary selection. If he decides to change the appointment and select the no hotel option, then we can show itineraries without, otherwise he sees the itinerary with hotels
 -Allow in hotel selection a card that says "do not book me a hotel for this night"

The major change therefor is, that we add a new hotel card that says "No Hotel", like we do in the flight options screen. 
This card should always appear as 1st card.

**Comment by davidtran** [comment]
I understand the second behavior

Can you visualize it? I need to know exactly where is should show it.
"-Show the hotel nights in the itinerary selection. If he decides to change the appointment and select the no hotel option, then we can show itineraries without, otherwise he sees the itinerary with hotels"

**Comment by GrosR** [comment]
Show the hotel nights in the itinerary selection (you already do that): 

![image](https://cloud.githubusercontent.com/assets/11087531/17550947/d128f928-5ef7-11e6-970f-55eef0cbce96.png)

What I found out here: 
Currently, one of the cards displays e.g.: 
Hotel
Stay three nights in Stiftung Pfennigparade, Barlachstraße, Munich, Germany
Hotel selection will be in the next step. 

The issue here is, that the user might stay either 
- close by at the customer location
- close by the next meeting location
- at some place he wants to choose freely

So, the text on the card should be more neutral  and should just say: 

Hotel
Stay three nights in Hotels until the next meeting
Hotel selection will be in the next step.

**Comment by GrosR** [comment]
Just to add that if it was not clear already: 
- if someone choses "Do nothing", we can just go to the next appointment
- if one chooses add another appointment, we add another card and recalculate the sorting of all cards
- if one chooses to "stay in a hotel", you must add the "hotel selection process" to the current appointment, so that a user can select a hotel. 

Comment: The hotel features are quite basic in this release, so I am aware that a user would need the option to either
- book the same hotel at a location of his choice for more then 1 day
- book different hotels for different days at different locations, if he wants to travel in between two meetings to do some sightseeing
AND
-according to what a user does in between, 
     - we would have to offer trips in between the hotels
    - change the starting point for the next meeting to the address of the latest hotel night
etc. 

But we don´t cover these cases NOW in this release

**Comment by GrosR** [comment]
can be closed due to #128
